local gt = this.getroottable();
gt.Const.TipOfTheDay = [
	"Jako bracia walczymy, jako bracia giniemy!",
	"Tarcze można rozłupać toporami i niektórymi broniami dwuręcznymi.",
	"Jedne typy tarcz lepiej sprawdzają się przeciwko broni białej, a inne lepiej przeciwko broni dystansowej.",
	"Tarcze otrzymują niewielkie obrażenia za każdym razem, gdy użyje się ich do zatrzymania ataku.",
	"Krzaki mogą posłużyć za kryjówkę, jeśli nie chcesz, aby postać była widoczna z daleka.",
	"Postać posiadająca przewagę wysokości nad swym przeciwnikiem, trudniejsza jest do trafienia.",
	"Postacie widzą tym dalej, im wyższą pozycję zajmują.",
	"Posiadanie w drużynie ludzi z różnych środowisk i zawodów może pozwolić ci na podjęcie innych czynów w wydarzeniach.",
	"Otoczenie przeciwnika z wielu stron sprawia, że łatwiej jest go trafić.",
	"Rozważ umieszczenie kontuzjowanych postaci w rezerwie, do czasu aż wyleczą swe rany.",
	"Rozważ trzymanie zapasowych wojowników w rezerwie i posyłanie ich do boju od czasu do czasu, aby łatwiej ci było poradzić sobie z ewentualnymi stratami w ludziach.",
	"Celność broni dystansowej zmniejsza się wraz z odległością do celu.",
	"Nie musisz zgrywać bohatera, prowadzisz interes.",
	"Ludzie wywodzący się z różnych środowisk mogą odblokować nowe opcje i sposoby rozwiązania kontraktów oraz wydarzeń.",
	"Przeciągnij i upuść swoich ludzi na ekranie ekwipunku, by ustawić dowolną formację.",
	"Chybiony atak z dystansu może trafić pobliskie postacie, zwłaszcza jeśli stoją one na bezpośredniej linii strzału.",
	"Z łuków nie można strzelać, a kusz - przeładowywać, jeśli wróg zbliżył się do strzelca.",
	"Łuki sprawdzają się lepiej przeciwko nieopancerzonym celom.",
	"Sztylety można wykorzystać do dźgania w słabe miejsca i luki w pancerzu, by zadać bezpośrednie obrażenia zdrowia.",
	"Broń dystansowa najlepiej się sprawdza przy atakowaniu skupisk wrogów - kogoś w końcu trafisz.",
	"Rozważ postawienie szyku ściany tarcz, gdy wróg cię otoczy.",
	"Oszczędzaj energię podczas długich starć.",
	"Powodzenie w Battle Brothers rozbija się o to, by rozsądnie dobierać bitwy.",
	"Morale i zmęczenie nie mają wpływu na Nieumarłych.",
	"Kusze nie wymagają aż takich umiejętności jak łuki, by móc celnie z nich strzelać. Są jednak wolniejsze w użyciu.",
	"Każdy typ broni ma swoje zalety i wady.",
	"Niektóre trudne tereny, jak np. bagna, mają swoje kary do walki.",
	"Możesz zmienić wysokość kamery klawiszami + i -.",
	"Maczugi i buławy mogą ogłuszyć lub obezwładnić cele.",
	"Staraj się zostawić trochę koron na czarną godzinę.",
	"Miecze długie i dwuręczne mogą trafić wiele celów za jednym zamachem.",
	"Możesz przybliżać i oddalać widok za pomocą rolki myszy lub klawiszy Page Up i Page Down.",
	"Włócznie są dobrą bronią obronną, dzięki umiejętności \'Ściana włóczni\'.",
	"Spodziewaj się tego, że stracisz kilku ludzi.",
	"Przegrywanie jest fajne.",
	"Używaj terenu i wąskich przesmyków ku swojej przewadze.",
	"Im wyższy będą mieć poziom, tym wyższego żołdu zażądają twoi ludzie.",
	"Sprzedawanie towarów w bogatych, wielkich miastach da ci najwięcej koron.",
	"Używaj miotanych sieci, aby ograniczyć ruch wyjątkowo groźnych wrogów.",
	"Wykorzystuj handel, by mieć dodatkowe źródło przychodów.",
	"Zdobądź talenty \'Rotacja\' lub \'Praca Nóg\', aby zwiększyć swą mobilność na polu bitwy.",
	"Zasięg widzenia zostaje ograniczony w nocy, tak podczas walki, jak i na mapie świata.",
	"Szkielety są niezwykle odporne na ataki dystansowe i ogień.",
	"Ciężkie opancerzenie oferuje świetną ochronę, jednak znacznie spowalnia niosącą je postać i szybciej ją męczy.",
	"W ciężkich hełmach niełatwo się oddycha, a to tego ograniczają one pole widzenia.",
	"Młoty wojenne i nadziaki świetnie sobie radzą z ciężkim opancerzeniem.",
	"Gizarmą, Piką i długim toporem można atakować z odległości 2 pól, w przeciwieństwie do większości broni białej.",
	"Cepy ignorują premię do obrony od tarcz.",
	"Różne typy wrogów wymagają różnych taktyk, aby ich pokonać.",
	"Każdego wroga w grze da się pokonać, stosując odpowiednie podejście.",
	"Żaden człowiek pod względem fizycznym nie może się równać z dorosłym orkiem.",
	"Orkowie polegają na czystej sile i fizycznej sprawności.",
	"Gobliny nie mogą się równać z ludźmi pod względem fizycznym, więc muszą polegać na sprycie i brudnych sztuczkach.",
	"Berserkerzy Orków wzmacniają swój szał bojowy oraz odporność, im więcej krwi przeleją.",
	"Geisty to istoty zagubione pomiędzy światem fizycznym, a zaświatami, i ciągle przechodzą z jednego do drugiego.",
	"Geisty przetestują stanowczość twoich ludzi - im niższa, tym bardziej prawdopodobne, że spanikują i uciekną.",
	"Dwuręczne topory są w stanie trafić zarówno głowę, jak i tułów za jednym tylko ciosem.",
	"Dwuręczne topory mogą trafić do 6 celów przy jednym, okrężnym ciosie.",
	"Drogi są najszybszym sposobem podróżowania na lądzie, lecz nie zawsze tym najbezpieczniejszym.",
	"Lasy i knieje mogą skrywać w sobie wiele niebezpieczeństw.",
	"Zawsze miej ze sobą spory zapas prowiantu - inaczej twoi ludzie mogą zacząć głodować i zdezerterują!",
	"Wiedergangerzy to chodzące trupy.",
	"Trudny teren na mapie świata, taki jak góry czy grzęzawiska, sprawia, że twoi ludzie zużywają więcej prowiantu.",
	"Jeśli nie jesteś w stanie wygrać, wycofaj się, by przeżyć.",
	"Wycofuj się. Uciekaj. Nie tocz każdej bitwy do upadłego.",
	"Użyj klawisza Spacji, aby zatrzymać grę na mapie świata.",
	"Wyższe tereny, takie jak wzgórza czy góry pozwolą ci na dalsze obserwacje na mapie świata.",
	"Nie każdy kontrakt wart jest ryzyka.",
	"Próbuj negocjować wyższą zapłatę za swe kontrakty.",
	"Próbuj wynegocjować takie warunki kontraktu, które zapewnią ci najwyższą zapłatę.",
	"Nie każdą bitwę da się wygrać.",
	"Życie na tym świecie może być niewiele warte.",
	"Zdradzenie swego pracodawcy może na dłuższą metę przynieść niepożądane skutki.",
	"Niektóre części świata są bardziej niebezpieczne od reszty.",
	"Używaj przystani do szybkiego przemieszczania się po świecie.",
	"Niektórzy ludzie wykorzystają cię i odrzucą, gdy już na nic im się nie przydasz.",
	"Broń miotana może być zabójcza na krótkie dystanse, jednak jej celność znacząco spada, gdy cel jest znacznie oddalony.",
	"Wielce utalentowane postacie mogą się wywodzić z różnych środowisk.",
	"Wypróbuj tryb Ironman, aby doświadczyć Battle Brothers takiego, jakie być powinno.",
	"Broń dystansowa jest mniej celna w nocy - twoich wrogów też to dotyczy.",
	"Rozbij obóz, aby szybciej naprawić ekwipunek i wyleczyć swych ludzi.",
	"Użyj ALT + Prawy Przycisk Myszy, aby oznaczyć przedmioty do naprawy w twoim ekwipunku kompanii. Wyposażenie dźwigane przez twoich ludzi jest naprawiane automatycznie.",
	"Swoje przedmioty możesz za niewielką opłatą naprawić u kowala używając klawisza ALT + Prawy Przycisk Myszy.",
	"Złamanie kontraktu zezłości twego pracodawcę - zwłaszcza, gdy część lub całość zapłaty była z góry.",
	"Zamki i forty oferują tylko kontrakty szlacheckiego rodu, który jest właścicielem danej fortyfikacji.",
	"Szlachta daje kontrakty tylko sławnym i profesjonalnym kompaniom najemników.",
	"Jeśli negocjacje kontraktu źle się potoczą, zaszkodzi to twojej reputacji z potencjalnym pracodawcą.",
	"Oferty kontraktów możesz znaleźć w lewym górnym rogu na ekranie osady.",
	"Możesz znaleźć potężne nazwane przedmioty gdzieś z dala od cywilizacji, eksplorując lub podążając za plotkami z karczm.",
	"Umieranie wpisuje się w profesję najemnika.",
	"Pilnuj nastroju swoich ludzi. Gdy pozostaną niezadowoleni przez dłuższy czas, mogą zdezerterować!",
	"Jeśli wciąż przegrywasz z wrogiem, zmień swoją taktykę!",
	"Im większy oddział na mapie świata, tym wolniej się przemieszcza. Ciebie też to dotyczy.",
	"Używaj wojennych ogarów, aby zapolować na bardziej lotnych i uciekających wrogów.",
	"Użyj wytresowanego sokoła, aby odkryć pozycję ukrytych wrogów w trudnym terenie.",
	"Tasaki mogą zadawać krwawiące rany.",
	"Spełnianie ambicji podniesie nastrój każdego towarzysza i doda ci sławy, a czasem i jakąś wyjątkową nagrodę.",
	"Użyj CTRL + Lewy Przycisk Myszy, aby zaatakować sojusznicze oddziały na mapie świata. To działa tylko wtedy, gdy aktualnie nie masz zlecenia.",
	"Twoi ludzie będą na siebie nawzajem różnie reagować, w zależności od tego z jakiego środowiska się wywodzą.",
	"Ogłuszone postacie nie będą mogły wykonać ataku okazyjnego, gdy ktoś przemieści się w ich strefie kontroli.",
	"Gdy już zapoznasz się nieco z grą, spróbuj rozegrać kampanię na poziomie \'Doświadczony\' - to zalecany poziom trudności.",
	"Minimalna szansa na trafienie każdego ataku wynosi 5%, zaś maksymalna to 95%.",
	"Postacie mogą czasem zostać powalone w bitwie, zamiast od razu zostać zabite. Wówczas przeżyją z jakąś trwałą raną.",
	"Ucz się na własnych błędach. Nie powtarzaj ich w nadziei, że tym razem dopisze ci szczęście.",
	"Naturalnym środowiskiem Wilkorów jest las.",
	"Możesz włączyć szybsze tury SI w menu ustawień.",
	"Drzewa można ukryć w czasie walki klawiszem \'T\'.",
	"Obiekty blokujące pola można podświetlić klawiszem \'B\'.",
	"Wyższa sława odblokuje dostęp do trudniejszych kontraktów i lepszych zarobków.",
	"Jeśli plan zawiódł z powodu pecha, to może nie był to zbyt dobry plan.",
	"Wykonaj robotę. Przeżyj. Odbierz zapłatę.",
	"Gdy postać oczekuje podczas swoje tury, jej pozycja w kolejce tur nowej rundy zostaje określana z karą 25% do Inicjatywy.",
	"Szansa na trafienie 95% oznacza również, że masz 5% szansy na spudłowanie.",
	"Na talent \'Samotny Wilk\' nie mają wpływu psy wojenne ani sojusznicy nie będący częścią twojej kompanii.",
	"Talent \'Szybka Adaptacja\' redukuje wpływ losowości.",
	"Miej na uwadze, że wrogie obozowiska na wzgórzach są trudniejsze do zaatakowania, zwłaszcza jeśli mają umocnienia."
];

if (this.Const.DLC.Desert)
{
	local tips = [
		"Południowe państwa-miasta dokonały niezrównanych postępów w medycynie, astrologii i alchemii.",
		"Południowcy zwą sami siebie \'Złoconymi\' od swego boga, w którego blasku dziennie się wygrzewają.",
		"\'Zadłużeni\' de-facto są społeczną kastą niewolników w państwach-miastach.",
		"Południowe państwa-miasta zostały zbudowane na ruinach Starożytnego Imperium.",
		"Koczownicy są ludźmi z południa, którzy nie poddali się rządom państw-miast.",
		"Koczownicy są mistrzami w prowadzeniu pustynnych wojen i wykorzystują środowisko ku swej przewadze - włączając w to rzucanie ci nim prosto w twarz.",
		"Ifryt jest demoniczną istotą, która wstąpiła w kamienie, skały i ruchome piaski.",
		"Sztylet Qatal najlepiej sprawdza się w połączeniu z bronią, która potrafi ogłuszyć lub oszołomić przeciwników.",
		"Przeładowanie rusznicy zajmuje pełną turę - chyba że twoja postać ma mistrzostwo w \'Kuszach i Broni Palnej\'.",
		"Rusznica jest bronią dystansową, która może trafić do 6 celów przy jednym strzale, choć ma mniejszy zasięg niż łuki i kusze.",
		"Lanca Ogniowa zostaje przeładowana po każdej bitwie, tak jak bronie miotane.",
		"Mecze na arenie oferują szybki sposób na zarobek - jednak nie możesz podczas nich się wycofać ani złupić ciał poległych przeciwników.",
		"Turnieje na arenie są wyjątkowymi wydarzeniami o odmiennych zasadach. Walcz pięcioma ludźmi przez trzy kolejne rundy i wygraj sławny przedmiot!",
		"Co każde pięć walk na arenie, możesz wygrać element gladiatorskiego wyposażenia, którego normalnie nie można kupić.",
		"Ogniste Garnuszki można wykorzystać do zadawania obrażeń przeciwnikom, lub też do zablokowania ich ruchu i opóźnienia ich.",
		"Dymiące Garnuszki można wykorzystać, aby zapewnić sobie bezpieczny odwrót, nawet jeśli twoi ludzie zaprzątnięci są walką bezpośrednią.",
		"Moździerze państw-miast mogą być obsługiwane jedynie przez inżyniera, który przy nich stoi.",
		"W historii \'Łowcy Głów\' możesz po każdej bitwie z ludźmi brać jeńców i zmuszać ich do walki po twojej.",
		"W historii \'Gladiatorzy\' rozpoczynasz z trzeba potężnymi postaciami, jednak utrata ich wszystkich spowoduje koniec kampanii.",
		"Najmij niewalczących towarzyszy do swej świty, aby dostosować swą kampanię do twego stylu gry.",
		"Utraciłeś sławną tarczę na rzecz orków? Zatrudnij kowala do swej świty, a naprawisz każdy przedmiot, nawet jeśli jego wytrzymałość osiągnie zero.",
		"Szkolenie nowych rekrutów trwa zbyt długo? Zatrudnij sierżanta musztry, aby szybciej zdobywali doświadczenie..",
		"Napotykasz niewielu wrogich czempionów? Zatrudnij łowcę nagród, a znajdziesz ich więcej i otrzymasz nagrodę za każdego, którego ubijesz.",
		"Płacisz za dużo żołdu? Zatrudnij płatnika, aby zredukować wysokość wypłacanych wynagrodzeń.",
		"Zastanawiasz się, kto tędy przeszedł? Zatrudnij czujkę, a zyskasz więcej informacji z tropów na mapie świata.",
		"Zawsze brakuje ci amunicji i narzędzi? Zatrudnij szabrownika, aby odzyskać część wykorzystanej amunicji i zebrać narzędzia z wszelkich zniszczonych pancerzy.",
		"Pełny ekwipunek? Kup wózki i wozy dla swej kompanii na ekranie Świty.",
		"Odblokowujesz sloty w twojej świcie niewalczących towarzyszy poprzez zdobywanie sławy.",
		"Mordercze hieny, wędrujące po południowych pustyniach, mają silne szczęki, zdolne zmiażdżyć nawet metalowy pancerz i zadać krwawiące rany.",
		"Wypróbuj różnych towarzyszy ze świty, aby znaleźć takich, którzy najlepiej pasują do twego stylu gry i wybranego scenariusza."
	];
	this.Const.TipOfTheDay.extend(tips);
}

if (this.Const.DLC.Wildmen)
{
	local tips = [
		"Północ jest zamieszkała przez zaciekłe barbarzyńskie plemiona.",
		"Barbarzyńcy często przytłaczają swych wrogów na początku bitwy, lecz szybko się męczą.",
		"Północne ogary są wytrzymalsze niż południowe psy, jednak ustępują im szybkością i zwinnością.",
		"Rytmiczne brzmienie plemiennych bębnów zmniejsza co rundę nieznacznie zmęczenie wszystkich barbarzyńców na polu bitwy.",
		"Władcy bestii nie mogą strzelać z bata, aby sterować swymi dzikimi wojennymi machinami, gdy są zaprzątnięci w bezpośredniej walce z wrogiem.",
		"Barbarzyńcy nie mogą się doczekać spotkania ze swymi przodkami w zaświatach.",
		"Wypróbuj różne historie początkowe, aby dostosować kampanię do swego stylu gry.",
		"W scenariuszu \'Samotny Wilk\' będziesz mieć postać gracza w świecie. Jeśli zginiesz, kampania się zakończy.",
		"W scenariuszu \'Milicja Chłopska\' możesz wystawić do boju aż 16 ludzi jednocześnie.",
		"W scenariuszu \'Kultyści\' twój bóg będzie się domagał od ciebie ofiar, ale też wynagrodzi swych lojalnych wyznawców.",
		"W scenariuszu \'Banda Kłusowników\' będziesz się poruszać szybciej na mapie świata.",
		"W scenariuszu \'Karawana Kupiecka\' otrzymasz lepsze ceny podczas kupowania i sprzedawania.",
		"Proce wywołują efekt \'Oszołomienia\' przy trafieniu w głowę.",
		"Jako że kamienie są powszechne, procom nigdy nie zabraknie amunicji.",
		"Baty bojowe potrafią tymczasowo rozbroić przeciwników, powstrzymując ich od użycia umiejętności broni.",
		"Baty bojowe mogą zadawać krwawiące rany, choć sprawdzają się słabo przeciwko pancerzowi.",
		"Bułaty i szamsziry mają znacznie większą szansę na zadanie paskudnych ran, gdy trafią celu."
	];
	this.Const.TipOfTheDay.extend(tips);
}

if (this.Const.DLC.Unhold)
{
	local tips = [
		"Zamarznięte pustkowia północy są domem dla olbrzymich bestii, nie widzianych nigdzie indziej.",
		"Lindwurm jest bezskrzydłym, dwunożnym smokiem, przypominającym wielkiego węża.",
		"Istnieją różne regionalne warianty Unholdów.",
		"Unholdy potrafią szybko leczyć swe rany, także w bitwie.",
		"Drzewa poruszają się powoli.",
		"Alpy żywią się strachem i agonią ludzi mających koszmary.",
		"Zwiedzaj świat, aby odnaleźć legendarne lokacje z legendarnymi skarbami.",
		"Dwuręczne buławy doskonale nadają się do unieszkodliwiania pojedynczych przeciwników.",
		"Topory są nad wyraz skuteczne wobec drzew.",
		"Schrat to żyjące drzewo, istota z kory i drewna, z umysłem iście obcym.",
		"Używaj dodatków do pancerza, aby jeszcze bardziej ulepszyć i dostosować wyposażenie do swoich ludzi.",
		"Wiedźmy zniewolonym przez siebie osobom objawiają się jako młode damy o niebywałej urodzie.",
		"Wiedźmy znane są z tego, że dobijają złowrogich umów z ludźmi, którzy później tego żałują.",
		"Wiedźma może rzucić klątwę na jednego z twoich ludzi, by odczuwał ten sam ból, co ona.",
		"Webknechty zadają dodatkowe obrażenia celom, które są uwięzione w ich sieciach.",
		"Webknechty są tym pewniejsze siebie, w im większej są grupie.",
		"Webknecht to wielki pajęczak, który żyje w licznych koloniach w mrocznych częściach lasów, w każdej niemal części kontynentu.",
		"Zbieraj trofea z pokonanych bestii i każ taksydermiście wytworzyć z nich użyteczne przedmioty.",
		"Sprzedawanie trofeów z pokonanych bestii może być dochodowe. Zawsze też możesz zdobyć nowe.",
		"Rapiery są najpotężniejsze w rękach postaci o wysokiej inicjatywie.",
		"Użyj włóczni do rzucania, aby z daleka zniszczyć tarcze swych najniebezpieczniejszych przeciwników.",
		"Nachzehrery można często spotkać w południowych częściach świata.",
		"Alpy można spotkać niemal wyłącznie w nocy.",
		"Im dalej od cywilizacji, tym bardziej niebezpieczne bestie wędrują po ziemi.",
		"Mikstury,pomimo swych barwnych opisów, są głównie narkotykami, a postać może się od nich uzależnić.",
		"Przedawkowanie mikstur może doprowadzić postać do wymiotów i choroby.",
		"W historii \'Pogromcy Bestii\' łatwiej ci będzie tropić bestie i uzyskasz więcej trofeów z tych potworów, które zabijesz."
	];
	this.Const.TipOfTheDay.extend(tips);
}

