local gt = this.getroottable();

if (!("Strings" in gt.Const))
{
	gt.Const.Strings <- {};
}

gt.Const.Strings.CharacterNames <- [
	"Sigurd",
	"Zygfryd",
	"Hilmar",
	"Harald",
	"Sigbold",
	"Siegward",
	"Ulfert",
	"Kalle",
	"Espen",
	"Hagen",
	"Ewald",
	"Wenzel",
	"Ejnar",
	"Gunther",
	"Ivar",
	"Jannold",
	"Bertel",
	"Ingolf",
	"Wiedekind",
	"Egon",
	"Casimir",
	"Hilderich",
	"Friedrich",
	"Wendel",
	"Hasso",
	"Wilreich",
	"Hans",
	"Torhelm",
	"Fritz",
	"Mattis",
	"Birk",
	"Arnold",
	"Knut",
	"Adler",
	"Niels",
	"Elmer",
	"Ulfert",
	"Jost",
	"Tostig",
	"Bertram",
	"Albrecht",
	"Kunold",
	"Baldomar",
	"Dietmar",
	"Donbert",
	"Erwin",
	"Caspar",
	"Arne",
	"Edmund",
	"Kunibert",
	"Arnulf",
	"Eduard",
	"Meinolf",
	"Oskar",
	"Giselherr",
	"Reimar",
	"Wernhard",
	"Vander",
	"Werner",
	"Wigald",
	"Willibald",
	"Bjarne",
	"Henrik",
	"Ruthard",
	"Alrik",
	"Hubert",
	"Ernst",
	"Rudolf",
	"Hartbert",
	"Asgeir",
	"Horik",
	"Konrad",
	"Gerhard",
	"Hanke",
	"Guido",
	"Till",
	"Geralt",
	"Hartwig",
	"Thorben",
	"Gisbert",
	"Bruno",
	"Wigmar",
	"Gottfried",
	"Hakon",
	"Goswin",
	"Guntbert",
	"Eckbert",
	"Roger",
	"Gebhard",
	"Ralf",
	"Bernfried",
	"Guntram",
	"Ferdinand",
	"Leonhard",
	"Gerlach",
	"Helmer",
	"Gustav",
	"Gerold",
	"Gero",
	"Gerulf",
	"Emmerich",
	"Karl",
	"Dirk",
	"Falk",
	"Anzelm",
	"Diethelm",
	"Alvar",
	"Eberecht",
	"Wilhelm",
	"Hildebert",
	"Eryk",
	"Theudobald",
	"Havard",
	"Hakon",
	"Wolfgang",
	"Erling",
	"Kori",
	"Randolf",
	"Rollo",
	"Leif",
	"Lars",
	"Torsten",
	"Ingmar",
	"Asbjorn",
	"Steinar",
	"Reynhart",
	"Baldur",
	"Olaf",
	"Egil",
	"Magnus",
	"Gunnar",
	"Svein",
	"Carsten",
	"Eugen",
	"Anton",
	"Torvald",
	"Bernhard",
	"Einar",
	"Leberecht",
	"Ragnar",
	"Ottmar",
	"Otwin",
	"Balon",
	"Eberold",
	"Bertwin",
	"Oswald",
	"Rabe",
	"Reimund",
	"Wolf",
	"Eberhard",
	"Grimwald",
	"Hugo",
	"Hallstein",
	"Helfrich",
	"Haribert",
	"Balduin",
	"Waldemar",
	"Engelbert",
	"Tobjoern",
	"Erland",
	"Torkel",
	"Horst",
	"Thorismund",
	"Torleif",
	"Erhard",
	"Ulf",
	"Otto",
	"Hermann",
	"Heinrich",
	"Halsten",
	"Kettilmund",
	"Alfgeir",
	"Sorrel",
	"Hartmut",
	"Lothar",
	"Manfred",
	"Reinhold",
	"Alfred",
	"Dietrich",
	"Rupert",
	"Heimrad",
	"Sigmar",
	"Friso",
	"Landrich",
	"Lienhard",
	"Sigmund",
	"Reinhardt",
	"Kurt",
	"Bodo",
	"Volmar",
	"Liebwin",
	"Dieter",
	"Ulrich",
	"Eike",
	"Walram",
	"Malte",
	"Grimald",
	"Berthold",
	"Alberich",
	"Raban",
	"Rumold",
	"Witold",
	"Volker",
	"Volkhart",
	"Bertolf",
	"Walter",
	"Ortwin",
	"Humbert",
	"Adelmar",
	"Konrad",
	"Gernot",
	"Radulf",
	"Ludolf",
	"Giselher",
	"Adelbert",
	"Hjalmar",
	"Reiner",
	"Burkhard",
	"Winrich",
	"Wilderich",
	"Wilfried",
	"Robert",
	"Wolfram",
	"Raimund",
	"Thilmann",
	"Norman",
	"Ludger",
	"Alwin",
	"Markward",
	"Markolf",
	"Hadebrand",
	"Roderick",
	"Rambert",
	"Meinrad"
];
gt.Const.Strings.CharacterNamesFemale <- [
	"Ingrida",
	"Helga",
	"Irma",
	"Adela",
	"Birgita",
	"Bertha",
	"Borghilda",
	"Brunhilda",
	"Frida",
	"Gudrun",
	"Hilda",
	"Sigrida",
	"Matylda",
	"Gerhilda"
];
gt.Const.Strings.BarbarianNames <- [
	"Smud",
	"Hirguld",
	"Braum",
	"Grimner",
	"Harif",
	"Skallag",
	"Hylle",
	"Guder",
	"Asberk",
	"Iyrd",
	"Brand",
	"Obrun",
	"Jormal",
	"Joltul",
	"Jotnar",
	"Huggur",
	"Eirik",
	"Hafgufa",
	"Vaettir",
	"Frugar",
	"Lorki",
	"Rangvald",
	"Helheimer",
	"Brokkr",
	"Rork",
	"Hurik",
	"Skarbrand",
	"Sigbaal"
];
gt.Const.Strings.BarbarianTitles <- [
	"Pogromca",
	"Niszczyciel",
	"Burzyciel",
	"Grabieżca",
	"Zdobywca",
	"Pogromca",
	"Skaziciel",
	"Łupieżca",
	"Groźny",
	"Łowca Głów",
	"Pustoszyciel",
	"Czaszkogniot",
	"Łamignat",
	"Okrutny",
	"Wybraniec",
	"Waleczny",
	"Żelaznoboki",
	"Zakrwawiony",
	"Bestia",
	"Bestiokrwisty",
	"Wilczy Pazur",
	"Dziki",
	"Wykrwawiacz",
	"Miażdżyciel",
	"Wieczny"
];
gt.Const.Strings.SouthernNames <- [
	"Jamil",
	"Uthman",
	"Sayid",
	"Radwan",
	"Yazid",
	"Sahir",
	"Wahib",
	"Amira",
	"Aslam",
	"Atiq",
	"Sadan",
	"Ayman",
	"Hakan",
	"Hafas",
	"Sawar",
	"Shuyab",
	"Husan",
	"Hamdun",
	"Ayshun",
	"Jabir",
	"Zuhri",
	"Jifri",
	"Galib",
	"Tamim",
	"Jaquba",
	"Zawahir",
	"Shurayd",
	"Walid",
	"Musa",
	"Ubaid",
	"Harad",
	"Tariq",
	"Wasi",
	"Fariss",
	"Abani",
	"Mutar",
	"Uthman",
	"Tamim",
	"Tawid",
	"Zahiri",
	"Milad",
	"Nuh",
	"Abdari",
	"Junaid",
	"Malik",
	"Naser",
	"Jahaf",
	"Yazir",
	"Talha",
	"Sabti",
	"Harun",
	"Firi",
	"Rashid",
	"Hamdin",
	"Rasil",
	"Hayan",
	"Askari",
	"Barkud",
	"Husni",
	"Omar"
];
gt.Const.Strings.SouthernNamesLast <- [
	"Ibn Sahr",
	"Al-Dani",
	"Ibn Tayib",
	"Al-Sahl",
	"Ibn Hazam",
	"Ibn Jalaf",
	"Ibn Abbad",
	"Al-Tahir",
	"Al-Bajani",
	"Ibn Nusa",
	"Al-Faris",
	"Al-Wahiri",
	"Ibn Nuh",
	"Al-Kasim",
	"Ibn Husain",
	"Ibn Kamal",
	"Al-Fad",
	"Al-Baji",
	"Al-Aban",
	"Al-Salama",
	"Al-Haddad",
	"Al-Affan",
	"Al-Bakr",
	"Ibn Tasuf",
	"Al-Faradi",
	"Ibn Tayib",
	"Ibn Azid",
	"Ibn Wasi",
	"Al-Abbas",
	"Ibn Hamdi",
	"Al-Bahri",
	"Al-Zahir",
	"Ibn Salar",
	"Al-Sawid",
	"Ibn Hamdin",
	"Ibn Undi",
	"Ibn Asili",
	"Al-Tabar",
	"Al-Rundi",
	"Al-Siddiq",
	"Ibn Sabti",
	"Al-Fath",
	"Ibn Mansur",
	"Al-Sabbag",
	"Al-Benali",
	"Al-Aziz",
	"Ibn Jasib"
];
gt.Const.Strings.SouthernNamesLastGenitive <- [
	"Ibn Sahra",
	"Al-Daniego",
	"Ibn Tayiba",
	"Al-Sahla",
	"Ibn Hazama",
	"Ibn Jalafa",
	"Ibn Abbada",
	"Al-Tahira",
	"Al-Bajaniego",
	"Ibn Nusy",
	"Al-Farisa",
	"Al-Wahiriego",
	"Ibn Nuha",
	"Al-Kasima",
	"Ibn Husaina",
	"Ibn Kamala",
	"Al-Fada",
	"Al-Bajiego",
	"Al-Abana",
	"Al-Salamy",
	"Al-Haddada",
	"Al-Affana",
	"Al-Bakra",
	"Ibn Tasufa",
	"Al-Faradiego",
	"Ibn Tayiba",
	"Ibn Azida",
	"Ibn Wasiego",
	"Al-Abbasa",
	"Ibn Hamdiego",
	"Al-Bahriego",
	"Al-Zahira",
	"Ibn Salara",
	"Al-Sawida",
	"Ibn Hamdina",
	"Ibn Undiego",
	"Ibn Asiliego",
	"Al-Tabara",
	"Al-Rundiego",
	"Al-Siddiqa",
	"Ibn Sabtiego",
	"Al-Fatha",
	"Ibn Mansura",
	"Al-Sabbaga",
	"Al-Benaliego",
	"Al-Aziza",
	"Ibn Jasiba"
];
gt.Const.Strings.SouthernOfficerTitles <- [
	"Al-Jawlan",
	"Al-Talamanki",
	"Al-Mundir",
	"Al-Jasur Ibn Tawd",
	"Al-Jatami",
	"Al-Harun",
	"Al-Badir",
	"Al-Mayuriqi",
	"Al-Muharib",
	"Al-Tarabulusi Ibn-Asbat",
	"Al-Tasufin Ibn Habib",
	"Ibn Zayid",
	"Ibn Asmali",
	"Ibn Ibrahim",
	"Ibn Suhaliy"
];
gt.Const.Strings.GladiatorTitles <- [
	"Wojowniczy",
	"Król Areny",
	"Bezlitosny",
	"Dekapitator",
	"Niezrównany",
	"Niepokonany",
	"Brutalny",
	"Słabeusz",
	"Niewolnik",
	"Lew",
	"Hiena",
	"Zwycięski",
	"Ochotnik",
	"Rzeźnik",
	"Mistrz",
	"Gladiator",
	"Ogier",
	"Bestia",
	"Wspaniały",
	"Wściekły Byk",
	"Grzmot",
	"Stalowy Młot",
	"Niszczyciel",
	"Palownik"
];
gt.Const.Strings.NomadChampionTitles <- [
	"Skorpion",
	"Duch Piasków",
	"Wąż",
	"Plaga",
	"Srebrna Buława",
	"Pustynny Książę",
	"Nieuchwytny",
	"Cień",
	"Plądrownik",
	"Rabuś",
	"Koczowniczy Król",
	"Złodziej Piasków",
	"Zguba Kupców",
	"Pustynny Szczur",
	"Czarny Kieł",
	"Wąż",
	"Pustynny Najeźdźca",
	"Bicz Boży",
	"Przeklęty",
	"Kruk",
	"Koczownik",
	"Czerwony",
	"Wybraniec Złotnika",
	"Piaskowa Żmija",
	"Pielgrzym",
	"Wygnany",
	"Sęp",
	"Żywy Miraż",
	"Wolny Książę",
	"Książę Piasków",
	"Pyłowy Tancerz",
	"Złoty Sęp"
];
gt.Const.Strings.NomadChampionStandalone <- [
	"Skorpion",
	"Duch Piasków",
	"Wąż",
	"Plaga",
	"Srebrna Buława",
	"Pustynny Książę",
	"Nieuchwytny",
	"Cień",
	"Plądrownik",
	"Rabuś",
	"Koczowniczy Król",
	"Złodziej Piasków",
	"Zguba Kupców",
	"Pustynny Szczur",
	"Czarny Kieł",
	"Wąż",
	"Pustynny Najeźdźca",
	"Bicz Boży",
	"Przeklęty",
	"Kruk",
	"Koczownik",
	"Szkarłatny",
	"Wygnany",
	"Sęp",
	"Żywy Miraż",
	"Wolny Książę",
	"Książę Piasków",
	"Pyłowy Tancerz",
	"Złoty Sęp"
];
gt.Const.Strings.NomadChampionStandaloneGenitive <- [
	"Skorpiona",
	"Ducha Piasków",
	"Węża",
	"Plagi",
	"Srebrnej Buławy",
	"Pustynnego Księcia",
	"Nieuchwytnego",
	"Cienia",
	"Plądrownika",
	"Rabusia",
	"Koczowniczego Króla",
	"Złodzieja Piasków",
	"Zguby Kupców",
	"Pustynnego Szczura",
	"Czarnego Kła",
	"Węża",
	"Pustynnego Najeźdźcy",
	"Bicza Bożego",
	"Przeklętego",
	"Kruka",
	"Koczownika",
	"Szkarłatnego",
	"Wygnanego",
	"Sępa",
	"Żywego Mirażu",
	"Wolnego Księcia",
	"Księcia Piasków",
	"Pyłowego Tancerza",
	"Złotego Sępa"
];
gt.Const.Strings.DesertDevilChampionTitles <- [
	"Skorpion",
	"Duch Piasków",
	"%randomsouthernname% Żmija",
	"%randomsouthernname% Mistrz Ostrza",
	"%randomsouthernname% Pustynny Diabeł",
	"%randomsouthernname% Nieuchwytny",
	"%randomsouthernname% Cień",
	"%randomsouthernname% Wąż",
	"Wir",
	"Pustynny Diabeł",
	"%randomsouthernname% Piaskowa Żmija",
	"%randomsouthernname% Wygnany",
	"%randomsouthernname% Tancerz Ostrza",
	"%randomsouthernname% Żwawy",
	"%randomsouthernname% Niepokonany",
	"%randomsouthernname% Pyłowy Tancerz",
	"%randomsouthernname% Migoczący Kant",
	"%randomsouthernname% Karmazynowy Kant",
	"%randomsouthernname% Latające Ostrze",
	"%randomsouthernname% Pyłowy Diabeł",
	"Pustynny Wicher",
	"Czarny Jastrząb"
];
gt.Const.Strings.ExecutionerChampionTitles <- [
	"Kat",
	"Srebrna Buława",
	"Grabieżca",
	"Zmora Kupców",
	"Bicz Boży",
	"Przeklęty",
	"Piaskowy Olbrzym",
	"Wybraniec Złotnika",
	"Góra",
	"Bułat",
	"%randomsouthernname% Ozłocony",
	"Szalejący Koczownik",
	"%randomsouthernname% Nieśmiertelny",
	"Zbieracz Głów",
	"Olbrzym",
	"Skała",
	"Pustynna Burza",
	"Rozbijacz Czaszek",
	"Ifrit",
	"%randomsouthernname% Lew"
];
gt.Const.Strings.DesertStalkerChampionTitles <- [
	"Skorpion",
	"Piaskowy Prześladowca",
	"Pustynny Prześladowca",
	"Orzeł",
	"Kruk",
	"Jastrząb",
	"Wysłannik Śmierci",
	"Mistrz Łucznik",
	"Myśliwy",
	"Łowca Głów",
	"Piaskowa Żmija",
	"Promyk Światła",
	"Dłoń Złotnika",
	"Sokole Oko",
	"Sęp",
	"Wąż",
	"Żądliciel",
	"Poszukiwacz Serc"
];
gt.Const.Strings.NobleTitles <- [
	"Hrabia",
	"Hrabia",
	"Baron",
	"Baron",
	"Książę"
];
gt.Const.Strings.VizierTitles <- [
	"Wezyr Wojny",
	"Wezyr Skarbnicy",
	"Wezyr Handlu",
	"Wielki Wezyr",
	"Mistrz Astrolog",
	"Wysoki Kapłan"
];
gt.Const.Strings.SellswordTitles <- [
	"Rzeźnik",
	"Berserker",
	"Pies",
	"Ogar",
	"Krwawy",
	"Wilk",
	"Ostrze",
	"Palownik",
	"Młodszy",
	"Starszy",
	"Bezlitosny",
	"Czerwony",
	"Czarny",
	"Zguba Orków",
	"Rycerzobójca",
	"Sokół"
];
gt.Const.Strings.SwordmasterTitles <- [
	"Legenda",
	"Mistrz",
	"Szermierz",
	"Szybki",
	"Żwawe Ostrze",
	"Wąż",
	"Chyży",
	"Tancerz Ostrza",
	"Niepokonany",
	"Niepobity",
	"Czempion",
	"Mistrz Królestwa",
	"Starszy",
	"Niezrównany",
	"Umiejętny",
	"Latające Ostrze",
	"Tańczące Ostrze"
];
gt.Const.Strings.HedgeKnightTitles <- [
	"Samotny Wilk",
	"Wilk",
	"Ogar",
	"Stalodzierżca",
	"Pogromca",
	"Olbrzym",
	"Góra",
	"Plugawiciel",
	"Rycerzobójca",
	"Błędny Rycerz",
	"Bicz Boży",
	"Upadły Rycerz",
	"Mężobójca",
	"Wygnany",
	"Wojenny Okrzyk",
	"Czaszkobiorca",
	"Rębacz"
];
gt.Const.Strings.MasterArcherNames <- [
	"%randomname% Szypnik",
	"Niechybiący",
	"%randomname% Mistrz Łucznik",
	"%randomname% Myśliwy",
	"%randomname% Snajper",
	"Sto Kroków",
	"%randomname% Grot",
	"%randomname% Łowca Głów",
	"Zabójcze Oko",
	"%randomname% Strzelec Wyborowy",
	"%randomname% Strzelec",
	"%randomname% Szybkostrzelny",
	"%randomname% Świszcząca Śmierć",
	"%randomname% Dźgacz",
	"Orzeł",
	"%randomname% Pewny Strzał",
	"%randomname% Celny"
];
gt.Const.Strings.MasonTitles <- [
	"Budowniczy",
	"Układacz Cegieł",
	"Architekt",
	"Czeladnik"
];
gt.Const.Strings.MilitiaTitles <- [
	"Poborowy",
	"Milicjant",
	"Piechur"
];
gt.Const.Strings.BrawlerTitles <- [
	"Twardoręki",
	"Kiereszownik",
	"Skała",
	"Ogier",
	"Żelazna Szczęka",
	"Zawadiaka"
];
gt.Const.Strings.PeddlerTitles <- [
	"Wąż",
	"Łasica",
	"Srebrny Język",
	"Markietan",
	"Handlarz",
	"Kupiec"
];
gt.Const.Strings.WitchhunterTitles <- [
	"Nocny Łowca",
	"Łowca Czarownic",
	"Egzorcysta",
	"Oprawca"
];
gt.Const.Strings.GravediggerTitles <- [
	"Grabarz",
	"Łopaciarz",
	"Grobownik",
	"Osobliwy"
];
gt.Const.Strings.RatcatcherTitles <- [
	"Długonosy",
	"Szczur",
	"Szczurołap",
	"Chłodny"
];
gt.Const.Strings.BastardTitles <- [
	"Bękart",
	"Błąd",
	"Dziecię Rogacza",
	"Tajemny Syn",
	"Kurwisyn",
	"Splamiony"
];
gt.Const.Strings.PilgrimTitles <- [
	"Wierzący",
	"Poszukiwacz",
	"Cudotwórca",
	"Nieskalany",
	"Biczownik",
	"Pielgrzym"
];
gt.Const.Strings.KnightNames <- [
	"Sir Roderick",
	"Sir Egidius",
	"Sir Henryk",
	"Sir Dankwart",
	"Sir Eisenherz",
	"Sir Geofram",
	"Sir Baranor",
	"Sir Wilhelm",
	"Sir Hildebrand",
	"Sir Hilmar",
	"Sir Severin",
	"Sir Starkwart",
	"Sir Elgast",
	"Sir Magnus",
	"Sir Burkhard",
	"Sir Silvan",
	"Sir Lambert",
	"Sir Kuno",
	"Sir Wenzel",
	"Sir Donatus",
	"Sir Albrecht",
	"Sir Hilderich",
	"Sir Zygmunt",
	"Sir Steinhart",
	"Sir Hermann",
	"Sir Eckhart",
	"Sir Guidobald",
	"Sir Theo",
	"Sir Eswig",
	"Sir Walram",
	"Sir Casimir",
	"Sir Magnus",
	"Sir Wighart",
	"Sir Otto",
	"Sir Sigismund",
	"Sir Erland",
	"Sir Erkenbrand",
	"Sir Theoderich",
	"Sir Lothar",
	"Sir Wolfhart",
	"Sir Balon",
	"Sir Valdemar",
	"Sir Giselherr",
	"Sir Engelbert",
	"Sir Lancel",
	"Sir Humbert",
	"Sir Emmerich",
	"Sir Grimm",
	"Sir Donbert",
	"Sir Robert",
	"Sir Wolfgang",
	"Sir Kettilmund",
	"Sir Konrad",
	"Sir Rupert",
	"Sir Harald",
	"Sir Roland",
	"Sir Rabe",
	"Sir Zygfryd",
	"Sir Kunibert",
	"Sir Dankrad",
	"Sir Leberecht"
];
gt.Const.Strings.OrcWarlordNames <- [
	"Illska Ghul",
	"Skabskra",
	"Urosh",
	"Kushtrum",
	"Goth Na Ari",
	"Obrokk",
	"Blok Sapat",
	"Gorash",
	"Mogtul",
	"Thraktar",
	"Gorgash-Ghul",
	"Maruk",
	"Warak Na Borash",
	"Urgat",
	"Durgash",
	"Skalleklyfta",
	"Margash Borash",
	"Borgash",
	"Goruk Sapat",
	"Karosh Urgat",
	"Horgash Ghul",
	"Naguk",
	"Shadok",
	"Bakh Lob",
	"Corgat",
	"Urmuk Ghul",
	"Mug Nadar",
	"Vras Ushtar",
	"Brulk Zogtar",
	"Sapat Blok",
	"Mosh Shagit",
	"Gajit Bukol",
	"Blot Kakok",
	"Thrak Talun",
	"Drod Kazan",
	"Oxshak",
	"Urdanog",
	"Trok Oborr",
	"Bolvag Shrub",
	"Ug Shatup",
	"Shatratog",
	"Buruk Skag",
	"Ilska Sapat",
	"Grug Zartum",
	"Grommok",
	"Ogrul",
	"Shura Nak"
];
gt.Const.Strings.BanditLeaderNames <- [
	"Rzeźnik",
	"%randomname% Nóż",
	"%randomname% Ubijacz",
	"Król %randomname%",
	"%randomname% Wół",
	"Wilk",
	"%randomname% Maruder",
	"%randomname% Wąż",
	"%randomname% Czteropalcy",
	"Barabasz Siarczany",
	"Rotor Kruczoczarny",
	"Baltazar Czarna Wrona",
	"Byk z %randomtown%",
	"%randomname% Krwawobrody",
	"%randomname% Pijaczyna",
	"Krwawy %randomname%",
	"Koszmarny %randomname%",
	"Świnia",
	"%randomname% Okrutny",
	"%randomname% Wyrzutek",
	"Rabusiowy Baron",
	"Czerwona Żmija",
	"%randomname% Zbój",
	"%randomname% Plaga",
	"Pan Rozbojów",
	"Łowca Głów",
	"Wielki %randomname%",
	"%randomname% Dzikus",
	"Niesławny %randomname%",
	"Groźba z %randomtown%",
	"%randomname% Czerwony",
	"Gunther Wyszczerzony",
	"%randomname% Hiena",
	"%randomname% Jastrząb",
	"%randomname% Szalony",
	"%randomname% Brutal",
	"%randomname% Szabrownik",
	"Lars Pomyleniec",
	"%randomname% Wolny",
	"Czarnooki Einhart",
	"Oswall Osobliwy",
	"Brokk Szalonooki",
	"%randomname% Blady Książę",
	"Plaga %randomtown%",
	"%randomname% Posępny",
	"Ingram Posępne Ostrze",
	"%randomname% Kieszonkowiec",
	"Mickel Miedzianogłowy",
	"Kacper Sakiewka",
	"Ottel Lodowate Serce",
	"Joost Koronobiorca",
	"Baltazar Bezzębny",
	"Walter Pająk",
	"August Grabarz",
	"Urban Dobrotliwy"
];
gt.Const.Strings.BanditLeaderNamesGenitive <- [
	"Rzeźnika",
	"%randomname%a Noża",
	"%randomname%a Ubijacza",
	"Króla %randomname%a",
	"%randomname%a Woła",
	"Wilka",
	"%randomname%a Marudera",
	"%randomname%a Węża",
	"%randomname%a Czteropalcego",
	"Barabasza Siarczanego",
	"Rotora Kruczoczarnego",
	"Baltazara Czarnej Wrony",
	"Byka z %randomtown%",
	"%randomname%a Krwawobrodego",
	"%randomname%a Pijaczyny",
	"Krwawego %randomname%a",
	"Koszmarnego %randomname%a",
	"Świni",
	"%randomname%a Okrutnego",
	"%randomname%a Wyrzutka",
	"Rabusiowego Barona",
	"Czerwonej Żmii",
	"%randomname%a Zbója",
	"%randomname%a Plagi",
	"Pana Rozbojów",
	"Łowcy Głów",
	"Wielkiego %randomname%a",
	"%randomname%a Dzikusa",
	"Niesławnego %randomname%a",
	"Groźby z %randomtown%",
	"%randomname%a Czerwonego",
	"Gunthera Wyszczerzonego",
	"%randomname%a Hieny",
	"%randomname%a Jastrzębia",
	"%randomname%a Szalonego",
	"%randomname%a Brutala",
	"%randomname%a Szabrownika",
	"Larsa Pomyleńca",
	"%randomname%a Wolnego",
	"Czarnookiego Einharta",
	"Oswalla Osobliwego",
	"Brokka Szalonookiego",
	"%randomname%a Bladego Księcia",
	"Plagi %randomtown%",
	"%randomname%a Posępnego",
	"Ingrama Posępne Ostrze",
	"%randomname%a Kieszonkowca",
	"Mickela Miedzianogłowego",
	"Kacpra Sakiewki",
	"Ottela Lodowate Serce",
	"Joosta Koronobiorcy",
	"Baltazara Bezzębnego",
	"Waltera Pająka",
	"Augusta Grabarza",
	"Urbana Dobrotliwego"
];
gt.Const.Strings.KrakenNames <- [
	"Ogg-Sattoth Wielki Pożeracz",
	"Kha-Athlu Wszystkokończący",
	"Shaggaruth Nieskończony",
	"Gla-Oth Bezkresna Paszcza",
	"Gu-Shogg Tysiącręki Młocarz",
	"Chtan-Nahitil Pożeracz Wszystkiego",
	"Xa-Shutar Pożeracz Światów",
	"Thohochoth Wszystkokończący",
	"Naccorath Wieczny",
	"Xapocathlu Niepowstrzymany"
];
gt.Const.Strings.AncientDeadNames <- [
	"Brasus",
	"Gudila",
	"Ostracon",
	"Dardanos",
	"Duras",
	"Mucatra",
	"Cothelas",
	"Arzaru",
	"Decalus",
	"Akamas",
	"Kavaros",
	"Comoscius",
	"Moskon",
	"Rholes",
	"Tarbus",
	"Apulon",
	"Napucon",
	"Barsobis",
	"Sirus",
	"Marnis",
	"Burrus",
	"Telephos",
	"Terebus",
	"Damastes",
	"Megerus",
	"Ianoton",
	"Cyrenos",
	"Haganon",
	"Neritos",
	"Seleukus",
	"Nomion",
	"Bacenor",
	"Caston",
	"Elpidus",
	"Aristes",
	"Morsimus",
	"Athenades",
	"Bacius"
];
gt.Const.Strings.AncientDeadTitles <- [
	"Przywrócony",
	"Odnowiciel",
	"Starożytny",
	"Niszczyciel",
	"Strażnik",
	"Myśliwy",
	"Drugi",
	"Herold",
	"Niezakopany",
	"Zapomniany",
	"Protektor",
	"Zasłużony",
	"Obrońca",
	"z Północy",
	"Wspaniały",
	"Hołdowany"
];
gt.Const.Strings.GoblinNames <- [
	"Nox",
	"Grubb",
	"Sharax",
	"Zuggut",
	"Grisnik",
	"Zatak",
	"Finex",
	"Zugtakr",
	"Velok",
	"Zatox",
	"Naxanix",
	"Vlixix",
	"Snarf",
	"Ratox",
	"Skrork",
	"Wruzak",
	"Drozub",
	"Zogrok",
	"Kulzik",
	"Xatox",
	"Vekuz",
	"Carax",
	"Drukzug",
	"Xeegox",
	"Sruzuz",
	"Drutnog",
	"Nogzak",
	"Wreek",
	"Zatush",
	"Kleklux"
];
gt.Const.Strings.GoblinTitles <- [
	"Dźgacz",
	"Zdradliwy",
	"Podrzynacz Gardeł",
	"Nożoliz",
	"Skórownik",
	"Łowca Głów",
	"Oczodźgacz",
	"Zgniłe Wątpia",
	"Długonosy",
	"Rozcinacz",
	"Nosogryz",
	"Rzeźnik",
	"Nieuchwytny",
	"Prześladowca",
	"Cieniołaz",
	"Mgłołaz",
	"Przebiegły",
	"Zdradziecki",
	"Hakowate Ostrze",
	"Patroszyciel",
	"Uszogryz",
	"Łamikark",
	"Nożownik"
];
gt.Const.Strings.GoblinTitlesGenitive <- [
	"Dźgacza",
	"Zdradliwego",
	"Podrzynacza Gardeł",
	"Nożoliza",
	"Skórownika",
	"Łowcy Głów",
	"Oczodźgacza",
	"Zgniłe Wątpia",
	"Długonosego",
	"Rozcinacza",
	"Nosogryza",
	"Rzeźnika",
	"Nieuchwytnego",
	"Prześladowca",
	"Cieniołaza",
	"Mgłołaza",
	"Przebiegłego",
	"Zdradzieckiego",
	"Hakowate Ostrze",
	"Patroszyciela",
	"Uszogryza",
	"Łamikarka",
	"Nożownika"
];
gt.Const.Strings.FallenHeroTitles <- [
	"Spróchniały",
	"Niepochowany",
	"Zmurszały",
	"Skalany",
	"Wskrzeszony",
	"Nieumierający",
	"Przeklęty",
	"Zepsuty",
	"Niezłomny",
	"Łamacz Przysiąg",
	"Zapomniany",
	"Utracony",
	"Upadły Bohater",
	"Okrutny",
	"Przywrócony",
	"Książę Rozkładu",
	"Pusty",
	"Duch",
	"Bezduszny",
	"Trumienny"
];
gt.Const.Strings.NecromancerNames <- [
	"Król Robaków",
	"%randomname% Nieumierający",
	"%randomname% Czarny",
	"%randomname% Nekromanta",
	"Mistrz Marionetek",
	"Nosiciel Zarazy",
	"Mroczny Mistrz",
	"Reanimator",
	"%randomname% Szalony",
	"%randomname% Nawiedzony",
	"Blady Książę",
	"Mistrz Nieumierania",
	"%randomname% Apostata",
	"%randomname% Wiedzący",
	"%randomname% Robaczywy",
	"%randomname% Przeklęty",
	"%randomname% Opętany",
	"%randomname% Oświecony"
];
gt.Const.Strings.OathbringerNames <- [
	"Strażnik Przysięgi",
	"%randomname% Dawca Przysięgi",
	"Młot Anzelma",
	"Tarcza Anzelma",
	"Miecz Anzelma",
	"Skradzione Męstwo Anzelma",
	"%randomname% Przysięgający",
	"%randomname% Krzyżowiec",
	"%randomname% Gorliwy",
	"%randomname% Pobożny",
	"%randomname% Oddany",
	"%randomname% Paladyn",
	"%randomname% Prawy"
];

