local gt = this.getroottable();

if (!("Strings" in gt.Const))
{
	gt.Const.Strings <- {};
}

gt.Const.Strings.ShieldNames <- [
	"Tarcza",
	"Szaniec",
	"Przedmurze",
	"Deska",
	"Mur",
	"Osłona",
	"Bezpiecznik",
	"Strażnik",
	"Obrońca",
	"Majdan",
	"Barykada",
	"Bariera",
	"Schronienie",
	"Bastion",
	"Forteca",
	"Straż",
	"Wał",
	"Opiekun",
	"Całun",
	"Skorupa"
];
gt.Const.Strings.ShieldNamesFemale <- [
	"Tarcza",
	"Deska",
	"Osłona",
	"Barykada",
	"Bariera",
	"Forteca",
	"Okowa",
	"Obrończyni",
	"Straż",
	"Strażniczka",
	"Opiekunka",
	"Skorupa"
];
gt.Const.Strings.ShieldNamesMale <- [
	"Szaniec",
	"Mur",
	"Bezpiecznik",
	"Strażnik",
	"Obrońca",
	"Majdan",
	"Schron",
	"Bastion",
	"Strażnik",
	"Wał",
	"Opiekun",
	"Całun"
];
gt.Const.Strings.SwordNames <- [
	"Ścinacz",
	"Krajarka",
	"Ostrze",
	"Odcinacz",
	"Tasak",
	"Miecz",
	"Zabijacz",
	"Litość",
	"Uśmiercacz",
	"Sztych",
	"Wojenne Ostrze",
	"Długie Ostrze",
	"Przelewacz Krwi",
	"Klinga",
	"Przebłysk",
	"Rozliczacz",
	"Mściciel",
	"Czerwone Rzeki",
	"Żądlik",
	"Błysk",
	"Uderzacz",
	"Brzytwa",
	"Brzeszczot",
	"Krawędź",
	"Wichrowe Ostrze",
	"Żwawa Klinga"
];
gt.Const.Strings.SwordNamesFemale <- [
	"Krajarka",
	"Litość",
	"Krawędź",
	"Klinga",
	"Brzytwa",
	"Żwawa Klinga"
];
gt.Const.Strings.SwordNamesMale <- [
	"Ścinacz",
	"Krajacz",
	"Odcinacz",
	"Tasak",
	"Miecz",
	"Sztych",
	"Zabijacz",
	"Uśmiercacz",
	"Przelewacz Krwi",
	"Przebłysk",
	"Rozliczacz",
	"Mściciel",
	"Żądlik",
	"Błysk",
	"Uderzacz",
	"Brzeszczot"
];
gt.Const.Strings.SabreNames <- [
	"Zakrzywione Ostrze",
	"Szabla",
	"Dekapitator",
	"Łukowate Ostrze",
	"Sierp",
	"Półksiężyc",
	"Południowa Gwiazda",
	"Szamszir",
	"Bułat"
];
gt.Const.Strings.SabreNamesFemale <- [
	"Zakrzywiona Klinga",
	"Szabla",
	"Łukowata Klinga",
	"Południowa Gwiazda"
];
gt.Const.Strings.SabreNamesMale <- [
	"Dekapitator",
	"Sierp",
	"Półksiężyc",
	"Szamszir",
	"Bułat"
];
gt.Const.Strings.CleaverNames <- [
	"Rębacz",
	"Rozpruwacz",
	"Ścinacz",
	"Krajacz",
	"Odcinacz",
	"Tasak",
	"Dekapitator",
	"Burzyciel",
	"Krwioprzelewacz",
	"Krwiopij",
	"Obłęd",
	"Krajacz",
	"Tasak Wojenny",
	"Patroszyciel",
	"Ciałorąb",
	"Mięsny Topór",
	"Mielnik",
	"Siekacz",
	"Rozszarpywacz",
	"Maglownik",
	"Nacinacz",
	"Kastrator",
	"Okaleczacz",
	"Ciemiężyciel",
	"Rozpruwacz"
];
gt.Const.Strings.WhipNames <- [
	"Bicz",
	"Jęzor",
	"Wąż",
	"Piorun",
	"Dusiciel",
	"Chwytacz",
	"Smagacz",
	"Kaziciel",
	"Naganiacz"
];
gt.Const.Strings.AxeNames <- [
	"Rozłupywacz",
	"Rębacz",
	"Topór",
	"Powalacz",
	"Furiat",
	"Mściciel",
	"Pogromca",
	"Rozbójnik",
	"Zwiastun",
	"Burzyciel",
	"Czaszkołam",
	"Podbójca",
	"Śmiercionios",
	"Mężobójca",
	"Niszczyciel",
	"Tarczołam",
	"Półksiężyc"
];
gt.Const.Strings.LongaxeNames <- [
	"Długi Topór",
	"Furiat",
	"Mściciel",
	"Rozbójnik",
	"Zwiastun",
	"Burzyciel",
	"Czaszkołam",
	"Śmiercionios",
	"Mężobójca",
	"Tarczołam",
	"Niszczyciel",
	"Drzeworąb",
	"Nasadzany Topór",
	"Łborąb",
	"Rozpruwacz",
	"Drzazgacz",
	"Rębak",
	"Grzmotonios",
	"Łamacz",
	"Rozłupywacz"
];
gt.Const.Strings.ThrowingAxeNames <- [
	"Toporki",
	"Ostrza",
	"Rozłupywacze",
	"Wirujące Śmierci",
	"Rozpruwacze",
	"Niszczyciele",
	"Rozdwajacze",
	"Burzyciele",
	"Zwiastuny",
	"Mężobójcy",
	"Nawałnice",
	"Półksiężyce",
	"Brutale",
	"Ubijaki",
	"Granie",
	"Pogromcy"
];
gt.Const.Strings.SpearNames <- [
	"Igła",
	"Palownik",
	"Włócznia",
	"Dźgacz",
	"Drzewce",
	"Rożen",
	"Szpikulec",
	"Pal",
	"Cierń",
	"Kolec",
	"Kołek",
	"Długa Włócznia",
	"Żwawy Kolec",
	"Przekłuwacz",
	"Obrońca",
	"Żądło",
	"Trzpień"
];
gt.Const.Strings.SpearNamesFemale <- [
	"Igła",
	"Włócznia",
	"Długa Włócznia",
	"Przekłuwaczka",
	"Obrończyni"
];
gt.Const.Strings.SpearNamesMale <- [
	"Palownik",
	"Dźgacz",
	"Rożen",
	"Szpikulec",
	"Pal",
	"Cierń",
	"Kolec",
	"Kołek",
	"Żwawy Kolec",
	"Przekłuwacz",
	"Obrońca",
	"Trzpień"
];
gt.Const.Strings.PikeNames <- [
	"Lanca",
	"Pal",
	"Kij",
	"Palik",
	"Palownik",
	"Pika Bojowa",
	"Pika",
	"Promień",
	"Rożen",
	"Żądło",
	"Kręgosłup",
	"Długa Pika",
	"Szydło",
	"Oślepiacz",
	"Iglica",
	"Srebrna Lanca",
	"Przekłuwacz"
];
gt.Const.Strings.PikeNamesFemale <- [
	"Lanca",
	"Pika Bojowa",
	"Pika",
	"Długa Pika",
	"Oślepiaczka",
	"Iglica",
	"Srebrna Lanca",
	"Przekłuwaczka"
];
gt.Const.Strings.PikeNamesMale <- [
	"Pal",
	"Kij",
	"Palik",
	"Palownik",
	"Promień",
	"Rożen",
	"Kręgosłup",
	"Oślepiacz",
	"Przekłuwacz"
];
gt.Const.Strings.BillNames <- [
	"Młócarz",
	"Gizarma",
	"Ścinacz",
	"Drzewiec",
	"Berdysz",
	"Chwytacz",
	"Sięgacz",
	"Wolołamca",
	"Krwioprzelewacz",
	"Siekacz",
	"Rębacz",
	"Wrogobójca",
	"Okaleczacz",
	"Chlastacz",
	"Haratacz",
	"Rozcinacz"
];
gt.Const.Strings.BillNamesFemale <- [
	"Młócarka",
	"Gizarma",
	"Ścinaczka",
	"Chwytaczka",
	"Krwioprzelewaczka",
	"Siekaczka",
	"Rębaczka",
	"Chlastaczka",
	"Harataczka",
	"Rozcinaczka"
];
gt.Const.Strings.BillNamesMale <- [
	"Młócarz",
	"Gizarma",
	"Ścinacz",
	"Drzewiec",
	"Berdysz",
	"Chwytacz",
	"Sięgacz",
	"Wolołamca",
	"Krwioprzelewacz",
	"Siekacz",
	"Rębacz",
	"Wrogobójca",
	"Okaleczacz",
	"Chlastacz",
	"Haratacz",
	"Rozcinacz"
];
gt.Const.Strings.GreatswordNames <- [
	"Wielki Miecz",
	"Zweihander",
	"Ostrze",
	"Klinga",
	"Długi Miecz",
	"Uśmiercacz",
	"Pogromca",
	"Dekapitator",
	"Kat",
	"Obrońca",
	"Orkobójca",
	"Honor",
	"Claymore",
	"Łotrza Zguba",
	"Długosiężca",
	"Rozcinacz",
	"Szpila",
	"Brzeszczot",
	"Miecz Wojenny",
	"Dwuręczniak",
	"Gassenhauer"
];
gt.Const.Strings.GreatswordNamesFemale <- [
	"Szpila",
	"Klinga"
];
gt.Const.Strings.GreatswordNamesMale <- [
	"Wielki Miecz",
	"Zweihander",
	"Długi Miecz",
	"Uśmiercacz",
	"Pogromca",
	"Dekapitator",
	"Kat",
	"Obrońca",
	"Orkobójca",
	"Honor",
	"Claymore",
	"Łotrza Zguba",
	"Długosiężca",
	"Rozcinacz",
	"Brzeszczot",
	"Miecz Wojenny",
	"Dwuręczniak",
	"Gassenhauer"
];
gt.Const.Strings.WarbrandNames <- [
	"Brzytwa Bojowa",
	"Kriegsmesser",
	"Beidhander",
	"Ostrze",
	"Długie Ostrze",
	"Uśmiercacz",
	"Pogromca",
	"Dekapitator",
	"Nieszczęście",
	"Brzeszczot",
	"Wojenne Ostrze",
	"Przecinak",
	"Pałasz",
	"Krawędź",
	"Klinga",
	"Uderzacz",
	"Mięsorąb",
	"Ćwiartownik"
];
gt.Const.Strings.WarbrandNamesFemale <- [
	"Brzytwa Bojowa",
	"Krawędź",
	"Klinga"
];
gt.Const.Strings.WarbrandNamesMale <- [
	"Kriegsmesser",
	"Beidhander",
	"Uśmiercacz",
	"Pogromca",
	"Dekapitator",
	"Brzeszczot",
	"Przecinak",
	"Pałasz",
	"Uderzacz",
	"Mięsorąb",
	"Ćwiartownik"
];
gt.Const.Strings.DaggerNames <- [
	"Drzazga",
	"Cierń",
	"Klin",
	"Dłuto",
	"Przecinak",
	"Żądło",
	"Kozik",
	"Bodkin",
	"Szydło",
	"Sztylet",
	"Upuszczacz Krwi",
	"Wiarołomca",
	"Jad",
	"Podstęp",
	"Mściciel",
	"Zdrajca",
	"Sercokłuj",
	"Puginał",
	"Goleń",
	"Kosa",
	"Igła",
	"Estok"
];
gt.Const.Strings.DaggerNamesFemale <- [
	"Drzazga",
	"Kosa",
	"Igła"
];
gt.Const.Strings.DaggerNamesMale <- [
	"Cierń",
	"Klin",
	"Przecinak",
	"Kozik",
	"Bodkin",
	"Sztylet",
	"Upuszczacz Krwi",
	"Wiarołomca",
	"Jad",
	"Podstęp",
	"Mściciel",
	"Zdrajca",
	"Sercokłuj",
	"Puginał",
	"Goleń",
	"Estok"
];
gt.Const.Strings.CrossbowNames <- [
	"Bełciarz",
	"Palownik",
	"Wypluwacz",
	"Gwoździarka",
	"Miotacz",
	"Strzelacz",
	"Katapulta",
	"Balista",
	"Kusza",
	"Kąsacz",
	"Penetrator",
	"Zdrajca",
	"Włóczniomiot",
	"Samostrzał",
	"Posłaniec",
	"Powtarzacz",
	"Łowca Olbrzymów",
	"Arbalet",
	"Sięgacz",
	"Wysłannik"
];
gt.Const.Strings.CrossbowNamesFemale <- [
	"Gwoździarka",
	"Miotaczka",
	"Katapulta",
	"Balista",
	"Kusza",
	"Zdrajczyni",
	"Łowczyni Olbrzymów",
	"Wysłanniczka"
];
gt.Const.Strings.CrossbowNamesMale <- [
	"Bełciarz",
	"Palownik",
	"Wypluwacz",
	"Miotacz",
	"Strzelacz",
	"Kąsacz",
	"Penetrator",
	"Zdrajca",
	"Włóczniomiot",
	"Samostrzał",
	"Posłaniec",
	"Powtarzacz",
	"Łowca Olbrzymów",
	"Arbalet",
	"Sięgacz",
	"Wysłannik"
];
gt.Const.Strings.BowNames <- [
	"Sięgacz",
	"Kijek",
	"Wielki Łuk",
	"Długi Łuk",
	"Łuk Wojenny",
	"Miotacz",
	"Uścisk",
	"Lot",
	"Refleks",
	"Wiatroszept",
	"Gwiezdny Warkocz",
	"Wojenna Pieśń",
	"Szept",
	"Przekłuwacz",
	"Mściciel",
	"Wicher",
	"Strzelacz",
	"Kąsacz",
	"Żądlik",
	"Kometa",
	"Meteor",
	"Burzonios",
	"Gradonios",
	"Gradobicie",
	"Strzałomiot",
	"Powróz",
	"Ścięgno",
	"Cięciwa"
];
gt.Const.Strings.BowNamesFemale <- [
	"Wojenna Pieśń",
	"Kometa",
	"Cięciwa"
];
gt.Const.Strings.BowNamesMale <- [
	"Sięgacz",
	"Kijek",
	"Wielki Łuk",
	"Długi Łuk",
	"Łuk Wojenny",
	"Miotacz",
	"Uścisk",
	"Lot",
	"Refleks",
	"Wiatroszept",
	"Gwiezdny Warkocz",
	"Szept",
	"Przekłuwacz",
	"Mściciel",
	"Wicher",
	"Strzelacz",
	"Kąsacz",
	"Żądlik",
	"Meteor",
	"Burzonios",
	"Gradonios",
	"Strzałomiot",
	"Powróz"
];
gt.Const.Strings.FlailNames <- [
	"Cep",
	"Wgniatacz",
	"Trzaskacz",
	"Bicz",
	"Sprawiedliwość",
	"Oczyszczacz",
	"Złośliwość",
	"Żniwiarz",
	"Lament",
	"Nienawiść",
	"Rozliczenie",
	"Ślepa Sprawiedliwość",
	"Zbawienie",
	"Batożyciel",
	"Chłostacz",
	"Klepacz",
	"Obtłuczacz",
	"Kosiarz",
	"Korbacz",
	"Kaziciel",
	"Latająca Gwiazda",
	"Napastnik",
	"Obijacz"
];
gt.Const.Strings.FlailNamesFemale <- [
	"Sprawiedliwość",
	"Złośliwość",
	"Nienawiść",
	"Ślepa Sprawiedliwość",
	"Latająca Gwiazda"
];
gt.Const.Strings.FlailNamesMale <- [
	"Cep",
	"Wgniatacz",
	"Trzaskacz",
	"Bicz",
	"Oczyszczacz",
	"Żniwiarz",
	"Lament",
	"Batożyciel",
	"Chłostacz",
	"Klepacz",
	"Obtłuczacz",
	"Kosiarz",
	"Korbacz",
	"Kaziciel",
	"Napastnik",
	"Obijacz"
];
gt.Const.Strings.MaceNames <- [
	"Zgniatacz",
	"Rozbijacz",
	"Miażdżyciel",
	"Drąg",
	"Buława",
	"Maczuga",
	"Mężobójca",
	"Czaszkołom",
	"Obuch",
	"Kieresznik",
	"Dominacja",
	"Dezolacja",
	"Wojenna Maczuga",
	"Baton",
	"Berło",
	"Królewska Buława",
	"Gruchot",
	"Obtłukiwacz",
	"Pukacz"
];
gt.Const.Strings.MaceNamesFemale <- [
	"Buława",
	"Maczuga",
	"Dominacja",
	"Dezolacja",
	"Wojenna Maczuga",
	"Królewska Buława"
];
gt.Const.Strings.MaceNamesMale <- [
	"Zgniatacz",
	"Rozbijacz",
	"Miażdżyciel",
	"Drąg",
	"Mężobójca",
	"Czaszkołom",
	"Obuch",
	"Kieresznik",
	"Baton",
	"Gruchot",
	"Obtłukiwacz",
	"Pukacz"
];
gt.Const.Strings.HammerNames <- [
	"Młot",
	"Podbijak",
	"Tłuczek",
	"Miażdżyciel",
	"Zbrojogniot",
	"Dziób",
	"Zgniatacz",
	"Kataklizm",
	"Młot Bojowy",
	"Rycerzobójca",
	"Grom",
	"Żelazołam",
	"Cypel",
	"Dziobak",
	"Stalogniot",
	"Zgrzytacz",
	"Rozrywacz"
];
gt.Const.Strings.JavelinNames <- [
	"Ciernie",
	"Kolce",
	"Igły",
	"Oszczepy",
	"Włócznie do Rzucania",
	"Pale",
	"Strzałki",
	"Szpikulce",
	"Kręgosłupy",
	"Gwoździe",
	"Lance",
	"Harpuny"
];
gt.Const.Strings.FencingSwordNames <- [
	"Żądlik",
	"Rozgardiasz",
	"Cierń",
	"Kąsacz",
	"Krawędź",
	"Iglica",
	"Klinga",
	"Ostrze",
	"Sercokłuj",
	"Krwioupuszczacz",
	"Przeszywacz",
	"Gracja",
	"Żwawa Klinga"
];
gt.Const.Strings.FencingSwordNamesFemale <- [
	"Kąsaczka",
	"Krawędź",
	"Iglica",
	"Klinga",
	"Przeszywaczka",
	"Gracja",
	"Żwawa Klinga"
];
gt.Const.Strings.FencingSwordNamesMale <- [
	"Żądlik",
	"Rozgardiasz",
	"Cierń",
	"Kąsacz",
	"Krawędź",
	"Sercokłuj",
	"Krwioupuszczacz",
	"Przeszywacz"
];
gt.Const.Strings.PolehammerNames <- [
	"Zgniatacz",
	"Miażdżyciel",
	"Wstrząs",
	"Trzęsioziem",
	"Żelazny Kąsacz",
	"Dziób",
	"Młot",
	"Grom",
	"Bramołom",
	"Wrotołom",
	"Młot Bojowy",
	"Grzmotnik"
];
gt.Const.Strings.ThreeHeadedFlailNames <- [
	"Ochsenherde",
	"Kocie Ogony",
	"Rozrywacz",
	"Chór",
	"Gradobicie",
	"Grad",
	"Lawina",
	"Obtłukiwacz",
	"Kaskada",
	"Popłoch",
	"Prysznic",
	"Brutalizator",
	"Batalion"
];
gt.Const.Strings.ThreeHeadedFlailNamesFemale <- [
	"Lawina",
	"Kaskada"
];
gt.Const.Strings.ThreeHeadedFlailNamesMale <- [
	"Ochsenherde",
	"Rozrywacz",
	"Chór",
	"Grad",
	"Obtłukiwacz",
	"Popłoch",
	"Prysznic",
	"Brutalizator",
	"Batalion"
];
gt.Const.Strings.SpetumNames <- [
	"Pal",
	"Trójząb",
	"Szpikulec",
	"Paliczek",
	"Kręgosłup",
	"Kolec",
	"Długa Pika",
	"Przeszywacz",
	"Oczodłub",
	"Iglica",
	"Srebrna Lanca",
	"Przekłuwacz"
];
gt.Const.Strings.SpetumNamesFemale <- [
	"Długa Pika",
	"Przeszywaczka",
	"Iglica",
	"Srebrna Lanca"
];
gt.Const.Strings.SpetumNamesMale <- [
	"Pal",
	"Trójząb",
	"Szpikulec",
	"Paliczek",
	"Kręgosłup",
	"Kolec",
	"Przeszywacz",
	"Oczodłub",
	"Przekłuwacz"
];
gt.Const.Strings.TwoHandedFlailNames <- [
	"Rozwalacz Czaszek",
	"Tarczogniot",
	"Miażdżyciel",
	"Czaszkołom",
	"Kościołam",
	"Okaleczacz",
	"Cep",
	"Kaziciel",
	"Zgniatacz",
	"Bicz",
	"Żniwiarz"
];
gt.Const.Strings.TwoHandedMaceNames <- [
	"Czaszkogniot",
	"Miażdżyciel",
	"Deptacz",
	"Pała",
	"Pałka",
	"Filar",
	"Zgniatacz",
	"Wojenna Maczuga",
	"Maczuga Olbrzyma",
	"Kamienna Pięść",
	"Grom",
	"Ziemiowstrząs"
];
gt.Const.Strings.TwoHandedMaceNamesFemale <- [
	"Pała",
	"Pałka",
	"Wojenna Maczuga",
	"Maczuga Olbrzyma",
	"Kamienna Pięść"
];
gt.Const.Strings.TwoHandedMaceNamesMale <- [
	"Czaszkogniot",
	"Miażdżyciel",
	"Deptacz",
	"Filar",
	"Zgniatacz",
	"Grom",
	"Ziemiowstrząs"
];
gt.Const.Strings.WarscytheNames <- [
	"Kosa Bojowa",
	"Kosiarz",
	"Sierp",
	"Ostrze",
	"Krawędź",
	"Kosa",
	"Żniwiarz",
	"Półksiężyc"
];
gt.Const.Strings.WarscytheNamesFemale <- [
	"Kosa Bojowa",
	"Klinga",
	"Krawędź",
	"Kosa",
	"Żniwiarka"
];
gt.Const.Strings.WarscytheNamesMale <- [
	"Kosiarz",
	"Sierp",
	"Żniwiarz",
	"Półksiężyc"
];
gt.Const.Strings.HandgonneNames <- [
	"Armata",
	"Ognisty Dech",
	"Prochowy Kij",
	"Ryk",
	"Piorun",
	"Ognisty Pręt",
	"Smoczy Jęzor",
	"Rusznica",
	"Pręt Gromów",
	"Ogniopluj"
];
gt.Const.Strings.HandgonneNamesFemale <- [
	"Armata",
	"Smocza Gęba",
	"Rusznica",
	"Ognioplujka"
];
gt.Const.Strings.HandgonneNamesMale <- [
	"Ognisty Dech",
	"Prochowy Kij",
	"Ryk",
	"Piorun",
	"Ognisty Pręt",
	"Smoczy Jęzor",
	"Pręt Gromów",
	"Ogniopluj"
];
gt.Const.Strings.SwordlanceNames <- [
	"Ostra Laska",
	"Ostry Kij"
];
this.Const.Strings.SwordlanceNames.extend(this.Const.Strings.WarscytheNames);
gt.Const.Strings.SwordlanceNamesFemale <- [
	"Ostra Laska"
];
this.Const.Strings.SwordlanceNamesFemale.extend(this.Const.Strings.WarscytheNamesFemale);
gt.Const.Strings.SwordlanceNamesMale <- [
	"Ostra Kij"
];
this.Const.Strings.SwordlanceNamesMale.extend(this.Const.Strings.WarscytheNamesMale);
gt.Const.Strings.OldWeaponPrefix <- [
	"Starożytna",
	"Praojcowska",
	"Rodowa",
	"Prastara",
	"Antyczna",
	"Odwieczna",
	"Trupia",
	"Dawno Utracona",
	"Zapomniana",
	"Stara",
	"Kuta",
	"",
	"Starodawna",
	"Złowieszcza",
	"Ponura",
	"Wiekowa",
	"Archaiczna",
	"Zabytkowa",
	"Pochowana",
	"Prekursorska",
	"Odwieczna",
	"Pradziejowa",
	"Niezwykła",
	"Szczątkowa",
	"Pamiątkowa",
	"Imperialna",
	"Legionowa",
	"Pradawna"
];
gt.Const.Strings.OldWeaponPrefixMale <- [
	"Starożytny",
	"Praojcowski",
	"Rodowy",
	"Prastary",
	"Antyczny",
	"Odwieczny",
	"Trupi",
	"Dawno Utracony",
	"Zapomniany",
	"Stary",
	"Kuty",
	"",
	"Starodawny",
	"Złowieszczy",
	"Ponury",
	"Wiekowy",
	"Archaiczny",
	"Zabytkowy",
	"Pochowany",
	"Prekursorski",
	"Odwieczny",
	"Pradziejowy",
	"Niezwykły",
	"Szczątkowy",
	"Pamiątkowy",
	"Imperialny",
	"Legionowy",
	"Pradawny"
];
gt.Const.Strings.BarbarianPrefix <- [
	"Zbroczona Krwią",
	"Zamarznięta",
	"Przerażająca",
	"Plemienna",
	"Barbarzyńska",
	"Zakrwawiona"
];
gt.Const.Strings.BarbarianPrefixMale <- [
	"Zbroczony Krwią",
	"Zamarznięty",
	"Przerażający",
	"Plemienny",
	"Barbarzyński",
	"Zakrwawiony"
];
gt.Const.Strings.BarbarianSuffix <- [
	"Wybrańca",
	"Rozbójnika",
	"Łupieżcy",
	"Podpalacza",
	"Przodków",
	"Czempiona",
	"Wodza",
	"Herszta",
	"Pogromcy",
	"Praojców",
	"z Północy",
	"Dawnych Lat",
	"Gniewu",
	"Rzezi",
	"Jatki",
	"Bogów",
	"Nieposłuszeństwa",
	"Bohaterów"
];
gt.Const.Strings.SouthernPrefix <- [
	"Południowa",
	"Koczownicza",
	"Piaskowa",
	"Gladiatorza",
	"Asasyńska",
	"Złocona",
	"Pustynna",
	"Prawdziwa",
	"",
	"Zabójcza",
	"Porządna",
	"Mistrzowska",
	"Zbalansowana",
	"Udoskonalona",
	"Sławna",
	"Zaufana",
	"Wspaniała",
	"Wygłodniała",
	"Gorzka",
	"Niesławna",
	"Cudowna",
	"Wezyrza",
	"Przerośnięta",
	"Krwawa",
	"Okrutna",
	"Mordercza",
	"Złośliwa",
	"Brutalna",
	"Zabójcza",
	"Złowroga",
	"Przerażająca",
	"Zdumiewająca",
	"Wyśmienita"
];
gt.Const.Strings.SouthernPrefixMale <- [
	"Południowy",
	"Koczowniczy",
	"Piaskowy",
	"Gladiatorzy",
	"Asasyński",
	"Złocony",
	"Pustynny",
	"Prawdziwy",
	"",
	"Zabójczy",
	"Porządny",
	"Mistrzowski",
	"Zbalansowany",
	"Udoskonalony",
	"Sławny",
	"Zaufany",
	"Wspaniały",
	"Wygłodniały",
	"Gorzki",
	"Niesławny",
	"Cudowny",
	"Wezyrzy",
	"Przerośnięty",
	"Krwawy",
	"Okrutny",
	"Morderczy",
	"Złośliwy",
	"Brutalny",
	"Zabójczy",
	"Złowrogi",
	"Przerażający",
	"Zdumiewający",
	"Wyśmienity"
];
gt.Const.Strings.SouthernSuffix <- [
	"Południa",
	"Złotnika",
	"Pustyni",
	"Piasków",
	"Wschodzącego Słońca",
	"Poranka",
	"Oazy",
	"Gwiazd",
	"Księżyca",
	"Splendoru",
	"Wspaniałości",
	"Oczyszczającego Ognia",
	"Boskiej Woli"
];
gt.Const.Strings.GoblinWeaponPrefix <- [
	"Ostra",
	"Szybka",
	"Szpiczasta",
	"Żądląca",
	"Strzępiasta",
	"Kolczasta",
	"Chytra",
	"Zdradziecka",
	"Skrytobójcza",
	"Okrutna",
	"Perfidna",
	"Lepka",
	"Plugawa",
	"Nikczemna"
];
gt.Const.Strings.GoblinWeaponPrefixMale <- [
	"Ostry",
	"Szybki",
	"Szpiczasty",
	"Żądlący",
	"Strzępiasty",
	"Kolczasty",
	"Chytry",
	"Zdradziecki",
	"Skrytobójczy",
	"Okrutny",
	"Perfidny",
	"Lepki",
	"Plugawy",
	"Nikczemny"
];
gt.Const.Strings.RandomWeaponPrefix <- [
	"",
	"Zabójcza",
	"Porządna",
	"Mistrzowskiej Ręki",
	"Wyważona",
	"Wyostrzona",
	"Ponura",
	"Najemnicza",
	"Sławna",
	"Zaufana",
	"Mistrzowska",
	"Bitewna",
	"Północna",
	"Zbójnicka",
	"Bohaterska",
	"Wspaniała",
	"Wygłodniała",
	"Zaciekła",
	"Niesławna",
	"Cudowna",
	"Przerośnięta",
	"Krwawa",
	"Okrutna",
	"Potężna",
	"Mordercza",
	"Złośliwa",
	"Dzika",
	"Brutalna",
	"Śmiercionośna",
	"Złowroga",
	"Straszliwa",
	"Przerażająca",
	"Zdumiewająca",
	"Wyśmienita"
];
gt.Const.Strings.RandomWeaponPrefixMale <- [
	"",
	"Zabójczy",
	"Porządny",
	"Mistrzowskiej Ręki",
	"Wyważony",
	"Wyostrzony",
	"Ponury",
	"Najemniczy",
	"Sławny",
	"Zaufany",
	"Mistrzowski",
	"Bitewny",
	"Północny",
	"Zbójnicki",
	"Bohaterski",
	"Wspaniały",
	"Wygłodniały",
	"Zaciekły",
	"Niesławny",
	"Cudowny",
	"Przerośnięty",
	"Krwawy",
	"Okrutny",
	"Potężny",
	"Morderczy",
	"Złośliwy",
	"Dziki",
	"Brutalny",
	"Śmiercionośny",
	"Złowrogi",
	"Straszliwy",
	"Przerażający",
	"Zdumiewający",
	"Wyśmienity"
];
gt.Const.Strings.RandomWeaponPrefixMulti <- [
	"",
	"Zabójcze",
	"Porządne",
	"Mistrzowskiej Ręki",
	"Wyważone",
	"Wyostrzone",
	"Ponure",
	"Najemnicze",
	"Sławne",
	"Zaufane",
	"Mistrzowskie",
	"Bitewne",
	"Północne",
	"Zbójnickie",
	"Bohaterskie",
	"Wspaniałe",
	"Wygłodniałe",
	"Zaciekłe",
	"Niesławne",
	"Cudowne",
	"Przerośnięte",
	"Krwawe",
	"Okrutne",
	"Potężne",
	"Mordercze",
	"Złośliwe",
	"Dzikie",
	"Brutalne",
	"Śmiercionośne",
	"Złowrogie",
	"Straszliwe",
	"Przerażające",
	"Zdumiewające",
	"Wyśmienite"
];
gt.Const.Strings.RandomArmorPrefix <- [
	"Kapitańska",
	"Mistrzowska",
	"Przednia",
	"Twarda",
	"Weterańska",
	"Cudna",
	"Krzepka",
	"Utwardzana",
	"Sławna",
	"Niesławna",
	"Najemnicza",
	"Nieugięta",
	"Rodowa",
	"Bojowa",
	"Wojenna",
	"Nieprzemijająca",
	"Mocna",
	"Niesforna",
	"Zaufana",
	"Zwycięska",
	"",
	"Wspaniała",
	"Cudowna",
	"Wybitna",
	"Prześwietna",
	"Dostojna",
	"Czcigodna",
	"Szacowna",
	"Podniosła",
	"Hołubiona",
	"Arcymistrzowska",
	"Monumentalna",
	"Sroga"
];
gt.Const.Strings.RandomArmorPrefixMale <- [
	"Kapitański",
	"Mistrzowski",
	"Przedni",
	"Twardy",
	"Weterański",
	"Cudny",
	"Krzepki",
	"Utwardzany",
	"Sławny",
	"Niesławny",
	"Najemniczy",
	"Nieugięty",
	"Rodowy",
	"Bojowy",
	"Wojenny",
	"Nieprzemijający",
	"Mocny",
	"Niesforny",
	"Zaufany",
	"Zwycięski",
	"",
	"Wspaniały",
	"Cudowny",
	"Wybitny",
	"Prześwietny",
	"Dostojny",
	"Czcigodny",
	"Szacowny",
	"Podniosły",
	"Hołubiony",
	"Arcymistrzowski",
	"Monumentalny",
	"Srogi"
];
gt.Const.Strings.RandomShieldPrefix <- [
	"",
	"Tęga",
	"Mistrzowska",
	"Twarda",
	"Niełamliwa",
	"Hartowana",
	"Utwardzana",
	"Krzepka",
	"Osławiona",
	"Nieprzezwyciężona",
	"Wspaniała",
	"Olbrzymia",
	"Niezłomna",
	"Lita",
	"Nieustępliwa",
	"Nietłukąca",
	"Niewzruszona",
	"Niezniszczalna",
	"Niewrażliwa",
	"Nieugięta",
	"Kolosalna"
];
gt.Const.Strings.RandomShieldPrefixMale <- [
	"",
	"Tęgi",
	"Mistrzowski",
	"Twardy",
	"Niełamliwi",
	"Hartowany",
	"Utwardzany",
	"Krzepki",
	"Osławiony",
	"Nieprzezwyciężony",
	"Wspaniały",
	"Olbrzymi",
	"Niezłomny",
	"Lity",
	"Nieustępliwy",
	"Nietłukący",
	"Niewzruszony",
	"Niezniszczalny",
	"Niewrażliwy",
	"Nieugięty",
	"Kolosalny"
];
gt.Const.Strings.WardogNames <- [
	"Byk",
	"Borsuk",
	"Zguba",
	"Diuk",
	"Kieł",
	"Hyde",
	"Mruk",
	"Zjawa",
	"Grond",
	"Wicher",
	"Fantom",
	"Śmiałek",
	"Zamieć",
	"Kościak",
	"Brant",
	"Sprint",
	"Drake",
	"Gil",
	"Jager",
	"Kąsacz",
	"Ochłap",
	"Earl",
	"Faust",
	"Szczęki",
	"Biegacz",
	"Ochłap",
	"Olof",
	"Błysk",
	"Król",
	"Wilk",
	"Ogar",
	"Błazen",
	"Cierń",
	"Ritter",
	"Varg",
	"Rozrabiaka",
	"Lord",
	"Cassio",
	"Pazur",
	"Kat",
	"Skoll",
	"Chudzielec",
	"Kolec",
	"Szary Kieł",
	"Duch",
	"Seff",
	"Wyjec",
	"Łazik",
	"Cujo",
	"Warczek",
	"Mrok",
	"Cień",
	"Suchy Kieł",
	"Amarog",
	"Grizli",
	"Długi Kieł",
	"Chrupacz",
	"Czerwony Ząb",
	"Maugrim",
	"Szpila",
	"Chłystek",
	"Kotołap",
	"Szybkołapy",
	"Piorun"
];

