local gt = this.getroottable();

if (!("Strings" in gt.Const))
{
	gt.Const.Strings <- {
		function getArticle( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "" : "";
		}

		function getArticleCapitalized( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "" : "";
		}

	};
}

if (!("Tactical" in gt.Const.Strings))
{
	gt.Const.Strings.Tactical <- {};
}

if (!("World" in gt.Const.Strings))
{
	gt.Const.Strings.World <- {};
}

gt.Const.Strings.Quantity <- [
	"1.",
	"2.",
	"3.",
	"4.",
	"5.",
	"6.",
	"7.",
	"8.",
	"9.",
	"10.",
	"11.",
	"12.",
	"13.",
	"14.",
	"15.",
	"16.",
	"17.",
	"18.",
	"19.",
	"20."
];
gt.Const.Strings.Amount <- [
	"brak",
	"jeden",
	"dwa",
	"trzy",
	"cztery",
	"pięć",
	"sześć",
	"siedem",
	"osiem",
	"dziewięć",
	"dziesięć",
	"jedenaście",
	"dwanaście",
	"trzynaście",
	"czternaście",
	"piętnaście",
	"szesnaście",
	"siedemnaście",
	"osiemnaście",
	"dziewiętnaście",
	"dwadzieścia",
	"dwadzieścia jeden",
	"dwadzieścia dwa",
	"dwadzieścia trzy",
	"dwadzieścia cztery",
	"dwadzieścia pięć",
	"dwadzieścia sześć",
	"dwadzieścia siedem",
	"dwadzieścia osiem",
	"dwadzieścia dziewięć",
	"trzydzieści"
];
gt.Const.Strings.AmountC <- [
	"Brak",
	"Jeden",
	"Dwa",
	"Trzy",
	"Cztery",
	"Pięć",
	"Sześć",
	"Siedem",
	"Osiem",
	"Dziewięć",
	"Dziesięć",
	"Jedenaście",
	"Dwanaście",
	"Trzynaście",
	"Czternaście",
	"Piętnaście",
	"Szesnaście",
	"Siedemnaście",
	"Osiemnaście",
	"Dziewiętnaście",
	"Dwadzieścia",
	"Dwadzieścia jeden",
	"Dwadzieścia dwa",
	"Dwadzieścia trzy",
	"Dwadzieścia cztery",
	"Dwadzieścia pięć",
	"Dwadzieścia sześć",
	"Dwadzieścia siedem",
	"Dwadzieścia osiem",
	"Dwadzieścia dziewięć",
	"Trzydzieści"
];
gt.Const.Strings.Difficulty <- [
	"Początkujący",
	"Doświadczony",
	"Ekspert"
];
gt.Const.Strings.EntityName <- [
	"Nekromanta",
	"Wiederganger",
	"Opancerzony Wiederganger",
	"Poległy Bohater",
	"Rachegeist",
	"Starożytny Auxiliary",
	"Starożytny Legionista",
	"Starożytny Gwardzista Honorowy",
	"Starożytny Kapłan",
	"Zdobywca",
	"Nekrosawant",
	"Geist",
	"Nachzehrer",
	"Młody Ork",
	"Ork Berserker",
	"Ork Wojownik",
	"Wódz Orków",
	"Ochotnik",
	"Strzelec Milicji",
	"Weteran Milicji",
	"Kapitan Milicji",
	"Łowca Nagród",
	"Chłop",
	"Pomocnik Karawany",
	"Strażnik Karawany",
	"Wóz Karawany",
	"Piechur",
	"Zweihander",
	"Halabardnik",
	"Kusznik",
	"Chorąży",
	"Sierżant",
	"Rycerz",
	"Osioł",
	"Bandyta Opryszek",
	"Bandyta Kłusownik",
	"Bandyta Strzelec",
	"Bandyta Najeźdźca",
	"Przywódca Bandytów",
	"Gobliński Zasadzkowicz",
	"Gobliński Harcownik",
	"Gobliński Nadzorca",
	"Gobliński Szaman",
	"Gobliński Wilczy Jeździec",
	"Wilk",
	"Pies Wojenny",
	"Opancerzony Pies Wojenny",
	"Najemnik",
	"Najemnik",
	"Mistrz Miecza",
	"Błędny Rycerz",
	"Mistrz Łucznik",
	"Katapulta Zielonoskórych",
	"Kultysta",
	"Wilkor",
	"Lindwurm",
	"Unhold",
	"Unhold",
	"Unhold",
	"Webknecht",
	"Jaja Webknechta",
	"Alp",
	"Wiedźma",
	"Schrat",
	"Podrostek",
	"Dzikus",
	"Kraken",
	"Irrlicht",
	"Poległy Zdrajca",
	"Mara Nocna",
	"Barbarzyński Thrall",
	"Barbarzyński Rozbójnik",
	"Barbarzyński Wybraniec",
	"Barbarzyński Dobosz",
	"Barbarzyński Władca Bestii",
	"Opancerzony Unhold",
	"Opancerzony Unhold",
	"Król Barbarzyńców",
	"Ogar Wojenny",
	"Ijirok",
	"Barbarzyński Szaleniec",
	"Wąż",
	"Ifrit",
	"Hiena",
	"Poborowy",
	"Strzelec",
	"Oficer",
	"Inżynier",
	"Asasyn",
	"Zadłużony",
	"Gladiator",
	"Moździerz",
	"Koczowniczy Rzezimieszek",
	"Koczowniczy Banita",
	"Koczowniczy Procarz",
	"Koczowniczy Łucznik",
	"Przywódca Koczowników",
	"Pustynny Prześladowca",
	"Koczowniczy Kat",
	"Tancerz Ostrza",
	"Obywatel",
	"Strażnik Wiedzy",
	"Zjawa Strażnika Wiedzy",
	"Filakteria",
	"Poszukiwacz Zaginionych Skarbów",
	"Wrzeszcząca Czaszka",
	"Dawca Przysięgi",
	"Cielisty Golem",
	"Większy Cielisty Golem",
	"Odnalazca Winy",
	"Wielki Wróżbita",
	"Cielista Kołyska"
];
gt.Const.Strings.EntityNamePlural <- [
	"Nekromantów",
	"Wiedergangerów",
	"Opancerzonych Wiedergangerów",
	"Poległych Bohaterów",
	"Rachegeistów",
	"Starożytnych Auxiliary",
	"Starożytnych Legionistów",
	"Starożytnych Gwardzistów Honorowych",
	"Starożytnych Kapłanów",
	"Zdobywców",
	"Nekrosawantów",
	"Geistów",
	"Nachzehrerów",
	"Młodych Orków",
	"Orków Berserkerów",
	"Orków Wojowników",
	"Wodzów Orków",
	"Ochotników",
	"Strzelców Milicji",
	"Weteranów Milicji",
	"Kapitanów Milicji",
	"Łowców Nagród",
	"Chłopów",
	"Pomocników Karawany",
	"Strażników Karawany",
	"Wozów Karawany",
	"Piechurów",
	"Zweihanderów",
	"Halabardników",
	"Kuszników",
	"Chorążych",
	"Sierżantów",
	"Rycerzy",
	"Osłów",
	"Bandytów Opryszków",
	"Bandytów Kłusowników",
	"Bandytów Strzelców",
	"Bandytów Najeźdźców",
	"Przywódców Bandytów",
	"Goblińskich Zasadzkowiczów",
	"Goblińskich Harcowników",
	"Goblińskich Nadzorców",
	"Goblińskich Szamanów",
	"Goblińskich Wilczych Jeźdźców",
	"Wilków",
	"Psów Wojennych",
	"Opancerzonych Psów Wojennych",
	"Najemników",
	"Najemników",
	"Mistrzów Miecza",
	"Błędnych Rycerzy",
	"Mistrzów Łuczników",
	"Katapult Zielonoskórych",
	"Kultystów",
	"Wilkorów",
	"Lindwurmów",
	"Unholdów",
	"Unholdów",
	"Unholdów",
	"Webknechtów",
	"Jaj Webknechta",
	"Alpów",
	"Wiedźm",
	"Schratów",
	"Podrostków",
	"Dzikusów",
	"Krakenów",
	"Irrlichtów",
	"Poległych Zdrajców",
	"Mar Nocnych",
	"Barbarzyńskich Thrallów",
	"Barbarzyńskich Rozbójników",
	"Barbarzyńskich Wybrańców",
	"Barbarzyńskich Doboszów",
	"Barbarzyńskich Władców Bestii",
	"Opancerzonych Unholdów",
	"Opancerzonych Unholdów",
	"Królów Barbarzyńców",
	"Ogarów Wojennych",
	"Ijiroków",
	"Barbarzyńskich Szaleńców",
	"Węży",
	"Ifritów",
	"Hien",
	"Poborowych",
	"Strzelców",
	"Oficerów",
	"Inżynierów",
	"Asasynów",
	"Zadłużonych",
	"Gladiator",
	"Moździerzy",
	"Koczowniczych Rzezimieszków",
	"Koczowniczych Banitów",
	"Koczowniczych Procarzy",
	"Koczowniczych Łuczników",
	"Przywódców Koczowników",
	"Pustynnych Prześladowców",
	"Koczowniczych Katów",
	"Tancerzy Ostrza",
	"Obywateli",
	"Strażnik Wiedzy",
	"Zjawa Strażnika Wiedzy",
	"Filakterii",
	"Poszukiwaczy Zaginionych Skarbów",
	"Wrzeszczących Czaszek",
	"Dawcy Przysięgi",
	"Cielistych Golemów",
	"Większych Cielistych Golemów",
	"Odnalazców Winy",
	"Wielki Wróżbita",
	"Cielistych Kołysek"
];
gt.Const.Strings.Tactical.EntityName <- {
	Boulder = "Głaz",
	Ruin = "Ruina",
	Shrubbery = "Zarośla",
	Tree = "Drzewo",
	Brush = "Krzew",
	Cartwheel = "Stare Koło Wozu",
	RuinedPillar = "Zniszczony Filar",
	Cart = "Wózek Karawany",
	Donkey = "Osioł",
	Plant = "Roślina"
};
gt.Const.Strings.Tactical.EntityDescription <- {
	Boulder = "Duży głaz. Blokuje ruch i pole widzenia.",
	Ruin = "Ruiny z ery, która dawno już minęła.",
	Shrubbery = "Bardzo gęste zarośla, który blokują ruch i pole widzenia.",
	Tree = "Wielkie drzewo z masywnym pniem.",
	TreeSwamp = "To drzewo jest przegniłe i od dawna martwe.",
	TreeTrunk = "Pieniek w połowie przykryty w zanieczyszczonej wodzie.",
	Brush = "Bardzo gęsty krzew, który blokuje ruch i pole widzenia.",
	Cartwheel = "Stare i złamane koło wozu.",
	RuinedPillar = "TODO",
	Cart = "Wózek pełen towarów handlowych.",
	Donkey = "Osioł używany jako zwierzę pociągowe do ciężkich wozów.",
	Plant = "Egzotyczna roślina, która blokuje ruch i pole widzenia."
};
gt.Const.Strings.FootprintsType <- [
	"",
	"Północni żołnierze",
	"Pozłacani żołnierze",
	"Karawana",
	"Chłopi",
	"Oddział milicji",
	"Uchodźcy",
	"Bandyci",
	"Nieumarli",
	"Orkowie",
	"Gobliny",
	"Barbarzyńcy",
	"Koczownicy",
	"Wilkory",
	"Nachzehrery",
	"Hieny",
	"Węże",
	"Webknechty",
	"Unholdy",
	"Alpy",
	"Wiedźmy",
	"Schraty",
	"Kraken",
	"Ifrity",
	"Lindwurmy",
	"Najemnicy"
];
gt.Const.Strings.ShipNames <- [
	"Letnia Bryza",
	"Radosna Mgła",
	"Jęk Morza",
	"Sekret Korali",
	"Piaskowa Przystań",
	"Dama Morza",
	"Soliter",
	"Brunhilda",
	"Matylda",
	"Kometa",
	"Tetrarcha",
	"Lofjord",
	"Jesienny Wiatr",
	"Miażdżyciel",
	"Brakel",
	"Siedem Gwiazd",
	"Mroczny Omen",
	"Konkord",
	"Albatros",
	"Złoty Koń",
	"Morska Nimfa",
	"Pokrętny Los",
	"Dar Króla",
	"Łysy Mnich",
	"Złote Słońce",
	"Marność",
	"Bezwstydnik",
	"Szpon Tygrysa",
	"Jawor",
	"Szlachecki Goniec",
	"Blady Księżyc",
	"Członek Klanu",
	"Wojaż Wieloryba",
	"Pędziwiatr",
	"Czarna Mucha",
	"Ejnar Erikson",
	"Lindwurm",
	"Najlepszy",
	"Gryf",
	"Axford",
	"Bertha",
	"Mewa",
	"Belzebub"
];
gt.Const.Strings.MercenaryCompanyNames <- [
	"\x02c0elazne Kruki",
	"ZՄoty Zakon",
	"Miecze PoՄudnia",
	"Wilki z ChՄodnej Kniei",
	"Czarne Tarcze",
	"Kompania \x02c0elaznej Korony",
	"Miecze Radobrechta",
	"Ʉwiszcz\x0380ce StrzaՄy",
	"Lazurowe Dziki",
	"KieՄ i Moneta",
	"Czerwony Legion",
	"ZgՄodniaՄe Ogary",
	"Karmazynowe Sztylety",
	"Kompania Kr\x0480lewskiej Zguby",
	"Czarna Kompania",
	"Drudzy Synowie",
	"Druքyna Walthera",
	"Nosiciele Urazy",
	"NiedЄwiedzie Bernharda",
	"Srebrny Szpon",
	"\x02c0elazne Bractwo",
	"Kompania Zmory Ork\x0480w",
	"\x02c0elazne Przymierze",
	"NiezՄomna Tr\x0480jca",
	"Psy Wojny",
	"Legion Falkenberga",
	"Wolni Ludzie",
	"Panowie Wojny",
	"P\x0480Մnocna Kompania",
	"Powr\x0480t Zapomnianych",
	"BiaՄa Kompania",
	"MԄքob\x0480jcy",
	"Kompania Lodowatych Serc",
	"Kompania Pal\x0380cego SՄońca",
	"Garstka Wybranych",
	"Truposze",
	"Br\x0380zogՄowi",
	"Marklandzkie Piki",
	"Kamienna Straք",
	"Kr\x0480lob\x0480jcy",
	"Srebrne WՄ\x0480cznie",
	"\x02c0elazny Pakt",
	"Braterstwo Krwi",
	"Ostoja",
	"Przemarsz Ʉwitu",
	"Synowie Zimy",
	"Kompania Rzecznego Rodu",
	"Kompania PՄon\x0380cej Komety",
	"WspaniaՄa Kompania",
	"Prawowici Burzyciele",
	"Zapomniana Brygada",
	"Wybrańcy Bitwy",
	"Zwiastownicy Pokoju",
	"Tarcze Nocy",
	"Kundle",
	"Koτciani Straքnicy",
	"Utracony Legion"
];
gt.Const.Strings.NobleHouseNames <- [
	"Grimmund",
	"Weilburg",
	"Armsberg",
	"Gota",
	"Eisenstein",
	"Grauwall",
	"Rabenholt",
	"Sommerwein",
	"Winterhall",
	"Ruhmolt",
	"Adelreich",
	"Perowinger",
	"Eiglof",
	"Berengar",
	"Gunbald",
	"Goswin",
	"Adelheim",
	"Ammondt",
	"Bartholin",
	"Eberlin",
	"Folsach",
	"Hedin",
	"Horn",
	"Niedergard",
	"Rosenving",
	"Thurah",
	"Kaltenborn",
	"Krieger",
	"Steinwall",
	"Harkon",
	"Osten"
];
gt.Const.Strings.CityStateNames <- [
	"Dahab",
	"Kabira",
	"Ras Sanan",
	"Tanwir",
	"Azim Shab",
	"Tarwa",
	"Hakim Al Ramal",
	"Karrakan",
	"Al-Hazred",
	"Al-Hazif",
	"Quadim",
	"Hikma",
	"El-Hadet",
	"Al-Anwar"
];
gt.Const.Strings.CityStateTitles <- [
	"Państwo-Miasto",
	"Miasto",
	"Protektorat",
	"Królestwo",
	"Wielkie Miasto",
	"Wolne Miasto",
	"Święte Miasto"
];
gt.Const.Strings.BusinessReputation <- [
	"Zdradziecki",
	"Niekompetentny",
	"Nierzetelny",
	"Nieznany",
	"Rozpoznawany",
	"Rzetelny",
	"Kompetentny",
	"Profesjonalny",
	"Szanowany",
	"Osławiony",
	"Świetny",
	"Wspaniały",
	"Baśniowy",
	"Legendarny",
	"Niepokonany",
	"Nieśmiertelny"
];
gt.Const.Strings.MoralReputation <- [
	"Budzący Postrach",
	"Okrutny",
	"Bezlitosny",
	"Małoduszny",
	"Neutralny",
	"Neutralny",
	"Życzliwy",
	"Dobry",
	"Rycerski",
	"Święty"
];
gt.Const.Strings.Relations <- [
	"Wrogie",
	"Zagrażające",
	"Nieprzyjazne",
	"Chłodne",
	"Neutralne",
	"Neutralne",
	"Otwarte",
	"Przyjazne",
	"Bardzo Przyjazne",
	"Sojusznicze"
];
gt.Const.Strings.Tactical.TerrainName <- [
	"Brak",
	"Polna Droga",
	"Gliniana Droga",
	"Brukowana Droga",
	"Łąka",
	"Gleba",
	"Las",
	"Błotnista Ziemia",
	"Zarośla",
	"Mętna Woda",
	"Step",
	"Suchy Step",
	"Tundra",
	"Śnieg",
	"Płytki Śnieg",
	"Kamień",
	"Kamień",
	"Piasek",
	"Płycizna"
];
gt.Const.Strings.Tactical.TerrainDescription <- [
	"Brak",
	"Droga gruntowa, powstała w wyniku ciągłego używania tej ścieżki przez ludzi i zwierzęta.",
	"Prymitywna droga, składająca się z ubitej gliny.",
	"Brukowana droga, używana przez powozy i inne duże pojazdy.",
	"Krótka trawa na płaskim i twardym gruncie.",
	"Goła i płaska gleba z niemalże całkowitym brakiem roślinności.",
	"Ściółka leśna, pokryta grubą i miękką warstwą mchu.",
	"Ciemna i błotnista gleba.",
	"Głównie stała i pewny grunt, pokryty wysoką i miękką trawą.",
	"Płytka, mętna woda, pokrywająca miękka i grząską ziemię.",
	"Płaska i twarda ziemia, pokryta wysuszonymi trawami.",
	"Twarde skrawki ziemi, kompletnie wyschniętej od słońca i upału.",
	"Płaska i jałowa ziemia, pokryta szorstkimi trawami i chwastami.",
	"Zamarznięta ziemia, przykryta grubą warstwą śniegu.",
	"Zamarznięta ziemia, przykryta płytką warstwą śniegu.",
	"Gładkie skaliste podłoże, zapewniające stabilne oparcie dla stóp.",
	"Twarde skaliste podłoże.",
	"Parząco gorący piasek pustyni.",
	"Czysta i płytka woda"
];
gt.Const.Strings.UI <- {
	Introduction = "Stary tekst, nie ma sensu tłumaczyć. ;)",
	FleeDialogueConsequences = "Czasami lepiej jest wykonać taktyczny odwrót, by ujść z życiem. Twoi ludzie postarają się wówczas dotrzeć samodzielnie do krańców mapy, by móc bezpiecznie się wycofać. Jednakże wróg może ich dogonić, a każda osoba zaangażowana w walkę może nie być w stanie ujść bez szwanku, a nawet z własnym życiem.",
	RetreatDialogueConsequences = "Wrogowie zostali rozbici. Tych kilku, którzy uszli z życiem, rozpierzchło się w różnych kierunkach. Czy zamierzasz ich ścigać, by zdobyć ich głowy i mienie, czy też uznasz bitwę za już wygraną?"
};
gt.Const.Strings.AlpStateName <- [
	"",
	"Istnieje częściowo we snach",
	"Istnieje częściowo we snach",
	"Istnieje głównie we snach",
	"Istnieje głównie we snach"
];
gt.Const.Strings.BodyPartName <- [
	"ciało",
	"głowę"
];
gt.Const.Strings.ItemSlotName <- [
	"Ciało",
	"Głowa",
	"Główna Ręka",
	"Druga Ręka",
	"Akcesorium",
	"Sakwa"
];
gt.Const.Strings.World.TimeOfDay <- [
	"Świt",
	"Ranek",
	"Południe",
	"Popołudnie",
	"Wieczór",
	"Zmierzch",
	"Noc",
	"Świt"
];
gt.Const.Strings.Direction <- [
	"północ",
	"północny-wschód",
	"południowy-wschód",
	"południe",
	"południowy-zachód",
	"północny-zachód",
	"<undefined>"
];
gt.Const.Strings.Direction8 <- [
	"północ",
	"północny-wschód",
	"wschód",
	"południowy-wschód",
	"południe",
	"południowy-zachód",
	"zachód",
	"północny-zachód"
];
gt.Const.Strings.Terrain <- [
	"",
	"w oceanie",
	"na równinach",
	"na bagnach",
	"na wzgórzach",
	"w lesie",
	"w lesie",
	"w lesie",
	"w lesie",
	"w górach",
	"",
	"",
	"w śniegu",
	"na pustkowiach",
	"w tundrze",
	"na stepie",
	"na wybrzeżu",
	"na pustyni",
	"na mokradłach"
];
gt.Const.Strings.TerrainAlternative <- [
	"",
	"",
	"na równinach",
	"na bagnie",
	"na wzgórzu",
	"w lesie",
	"w lesie",
	"w lesie",
	"w lesie",
	"na górze",
	"na równinach",
	"na równinach",
	"w śniegu",
	"",
	"w tundrze",
	"na stepie",
	"",
	"na pustyni",
	"na mokradłach"
];
gt.Const.Strings.TerrainShort <- [
	"",
	"zatoka",
	"równiny",
	"bagno",
	"wzgórza",
	"las",
	"las",
	"las",
	"las",
	"góra",
	"",
	"",
	"śnieg",
	"pustkowie",
	"tundra",
	"step",
	"wybrzeże",
	"",
	"pustynia",
	"wzgórza",
	"mokradła"
];
gt.Const.Strings.TerrainRegionNames <- [
	[],
	[
		"Morze Burzliwe",
		"Krakeński Azyl",
		"Morze BiaՄych Koni",
		"Morze Tysi\x0380ca Mew",
		"GՄԄboka Toń",
		"Deszczowy Ocean",
		"Bezkresny Ocean",
		"Burzliwy Ocean",
		"Grzmi\x0380ce Morze",
		"Wielkie Morze",
		"SkՄԄbione Morze",
		"Morze PerՄowe",
		"Wyj\x0380ce Morze",
		"Morze Okrutne",
		"Ocean ʄukowatych PՄyw\x0480w",
		"Morze Szepcz\x0380cych Fal",
		"Morze Zmarszczone",
		"Morze Zielone",
		"Morze Zmiennych PՄyw\x0480w",
		"Zawodz\x0380cy Ocean",
		"Pieniste PՄycizny",
		"Ocean Mrocznych PՄyw\x0480w",
		"Migocz\x0380ca Toń",
		"Lazurowa Toń",
		"Zatoka Wzburzona",
		"Migocz\x0380ce GՄԄbie"
	],
	[
		"Trawolandia",
		"Przetacznikowe Pola",
		"R\x0480wninnowՄoτci",
		"Winolandia",
		"Nizinnisko",
		"Wietrznoziemie",
		"Szeroka Warta",
		"OmszaՄa Domena",
		"Kwieciste ʄ\x0380ki",
		"Skazoziemie",
		"Hrabstwo \x02c0wawych ObՄok\x0480w",
		"JasnowՄoτci",
		"Uroczysko Szybkostopych",
		"ʄaska WԄdrowcy",
		"Dolinoziemie",
		"Czystoziemie",
		"Zielone FaՄdy",
		"Wieprzoludy",
		"\x02c0ytokՄosy",
		"PՄytkobr\x0480d",
		"Dwa Pola",
		"Kr\x0480lomՄyn",
		"Sieczkoziemie",
		"W\x0380wozowa Dolina",
		"Fl\x0380drofaՄdzie",
		"Kindon",
		"Zielonowody",
		"ʄosiowa Grań",
		"Altmark",
		"Neumark",
		"Jasne Uroczysko",
		"MiԄdzykresie",
		"Kraina ʄ\x0380k",
		"Mszana Dolina",
		"Szerokoakrze",
		"PoՄudniokwiecie",
		"Ʉwitoziemie",
		"DԄbowe ʄ\x0380ki",
		"Wichrowe Akry",
		"ʄ\x0380czane W\x0380wozy",
		"Wierzbowe Pola",
		"PiԄknolice Pastwiska",
		"Dolina SՄowik\x0480w",
		"Srebrzyste Polany",
		"Uroczysko Sercopieτni"
	],
	[
		"Czarne Moczary",
		"Trupie Stawy",
		"Smoliste Pola",
		"Torfowe Pola",
		"Dusz\x0380ce Bagno",
		"Upiorne Moczary",
		"Czarne GrzԄzawisko",
		"Koszmarne GrzԄzawisko",
		"MԄtne Bajora",
		"Uroczysko",
		"Czarnoziewy",
		"Wisielcze Bagno",
		"Gnojowisko",
		"Psie Moczary",
		"PosԄpne Bajoro",
		"PrzeklԄte Ziemie",
		"Ponure DoՄy",
		"Trzcinowisko",
		"\x02c0abowisko",
		"PajԄczy Gaj",
		"Upadek KsiԄcia",
		"Bezdenne DoՄy",
		"Truj\x0380ce Moczary",
		"Gaj \x02c0aboliz\x0480w",
		"Trupie DoՄy",
		"MokradՄa",
		"Moczary",
		"Czarne BՄoto",
		"Odludne Wrzosowiska",
		"Niecka Czarnych Opar\x0480w",
		"Bezkresna Niecka",
		"Torfowa Kotlina",
		"Nadrzeczne Polany",
		"Jelita PoՄudnia",
		"Lazurowe Moczary",
		"Bagno Tysi\x0380ca Luster",
		"W\x0380skie TrzԄsawisko",
		"Polany RozkՄadu",
		"Blade MokradՄa",
		"Dzikie Bajoro",
		"Szepcz\x0380ce Bagna",
		"Zakazane Wody",
		"Koszmarne Wrzosowisko"
	],
	[
		"Koτciany Kurhan",
		"Wzg\x0480rza Rycerskiego Topora",
		"Kopiec Czaszki",
		"Staroքytne Kopce",
		"Wzg\x0480rza Starozamcze",
		"Ziemiste Pag\x0480rki",
		"Wzg\x0480rzofaՄdy",
		"Staroքytne Kopce",
		"Mrucz\x0380ce Pag\x0480rki",
		"Ostre SkaՄy",
		"Mgliste Kurhany",
		"Skaliste Pag\x0480rki",
		"Kamienne Kurhany",
		"Rumowiskowe Kopce",
		"Upiorne Wzg\x0480rza",
		"Upiorne Kurhany",
		"Kamieniste Wyboje",
		"Warowne Wzg\x0480rza",
		"Kamyki Olbrzyma",
		"WԄքowe Wzg\x0480rza",
		"Skroniowe Wzg\x0480rza",
		"Wzg\x0480rza Rdzawych Jaskiń",
		"WiedЄmowe Wzg\x0480rza",
		"JaՄowcowe Pag\x0480rki",
		"Kopce BiaՄej Kozy",
		"Bulwy",
		"Wielka Rozci\x0380gՄoτƄ",
		"Szepcz\x0380ce Wzg\x0480rza",
		"Br\x0380zowe Wzg\x0480rza",
		"Wierzbowe Zbocza",
		"SzkarՄatne Wzg\x0480rza",
		"Olbrzymie Zbocza",
		"PosԄpne Wzg\x0480rza",
		"Skruszone Wzg\x0480rza"
	],
	[
		"Blady B\x0480r",
		"ZՄowroga Knieja",
		"PosԄpny B\x0480r",
		"Mroczna Knieja",
		"ʄajdaczy Las",
		"Dzicza Knieja",
		"Bandycka Ostoja",
		"Dolina Drzazgi",
		"PajԄcza Knieja",
		"Kleszczowisko",
		"Gaj Druida",
		"Lasy W\x0380tՄej GaՄ\x0380zki",
		"Zagajnik BiaՄego Wilka",
		"Krucza Ostoja",
		"Iglany Zagajnik",
		"Szumi\x0380ca Knieja",
		"B\x0480r OmszaՄej Sosny",
		"Wronie Gniazdo",
		"Czarny Las",
		"ʄotrzy G\x0380szcz",
		"PosԄpna Knieja",
		"Wilcza Knieja",
		"Czarny G\x0380szcz",
		"Szemrz\x0380cy B\x0480r",
		"Czarnociernia Puszcza",
		"Jeքowy G\x0380szcz",
		"Mglista Kryj\x0480wka",
		"Kresowa Dolina",
		"Ʉwi\x0380tynny Gaj",
		"NԄdzna Knieja",
		"Starcza Knieja",
		"GՄԄboka Kryj\x0480wka",
		"Papuքa Puszcza",
		"WiedЄmowa Knieja"
	],
	[],
	[
		"Staroքytny Las",
		"Spoczynek ʄowcy",
		"Dolina Jelenia",
		"Starorosty",
		"GԄstwiny",
		"Gaj \x02c0elaznego DԄbu",
		"Gaik Myτliwych",
		"Kr\x0480lewskie Ziemie",
		"Lesiste Lasy",
		"Lasy Lisa i Zaj\x0380ca",
		"Las ʄamliwych GaՄ\x0380zek",
		"Poroքysko",
		"Stara Knieja",
		"Zielona GԄstwina",
		"Mszany B\x0480r",
		"Mglisty B\x0480r",
		"Morze Drzew",
		"Drzewna Kraina",
		"Szepcz\x0380ce Gaje",
		"ZajԄcza Knieja",
		"Orzechowy Gaj",
		"WԄքowa Kryj\x0480wka",
		"Czarna Knieja",
		"Burzliwe Knieje",
		"Szeleszcz\x0380ca GԄstwina",
		"ZՄowroga Puszcza",
		"Lasy Szarej Ropuchy",
		"Las DrzewoՄaz\x0480w",
		"StrzԄpiasty Las",
		"Jelenie Pola",
		"Las DԄbowej Korony",
		"Bezowa Knieja",
		"Wi\x0380zowy Gaj",
		"Knieja Czarnokreta",
		"Strumyczy Las",
		"Wiosnolas",
		"Wiecznolas"
	],
	[
		"GliЄdzia Puszcza",
		"Ogniste Knieje",
		"Tl\x0380ce Lasy",
		"Rozքarzony Las",
		"Jaskrawy Gaj",
		"Lisi Las",
		"Letniokrzewie",
		"Ognioknieja",
		"Krwistoroτle",
		"Spaleniznokres",
		"Rdzawozwisy",
		"Krwawa Knieja",
		"PՄomienny Las",
		"Cynobrowy Las",
		"Karmazynowy Knieja",
		"Kasztanowa Knieja",
		"Czerwonolas",
		"Borsucza GԄstwina",
		"Brzozowa Knieja",
		"Wododrzewny Las",
		"Pirolas",
		"\x02c0ywokՄ\x0380cza Puszcza",
		"Bagienny Gaj",
		"\x02c0\x0480Մtolistna Domena",
		"Krwiokwitne Knieje",
		"Czerwonokora Knieja",
		"Gaj Ognistej SkaՄy"
	],
	[
		"KrԄgosՄup Ʉwiata",
		"Plecy Ʉpi\x0380cego Olbrzyma",
		"StrzԄpiaste Iglice",
		"Mur Bog\x0480w",
		"Koszmarne SkaՄy",
		"Kamienna Grań",
		"StrzԄpiasty Szczyt",
		"Srebrna Grań",
		"Mglisty Szczyt",
		"G\x0480ry \x02c0elazne",
		"Kozie Rogi",
		"Smocze ZԄby",
		"Wysokowzniosy",
		"Orli Lot",
		"Ponure Sklepienie",
		"Szara Szpica",
		"Strasznor\x0480g",
		"Kruczy Dzi\x0480b",
		"Przegrodzona G\x0480ra",
		"Szaniec",
		"GrudoՄby",
		"Brwiostocza",
		"Upadek Bohatera",
		"Ziewaj\x0380ca PrzeՄԄcz",
		"Mamucie Grzbiety",
		"WypuchniԄte Wyքyny",
		"ʄysa Korona",
		"Chmurzasty Czub",
		"G\x0480ry Wiecznej MgՄy",
		"Rzeziog\x0480ra",
		"Rozpadlina",
		"Grzmi\x0380ce Wierchy",
		"RozpadՄe Wyքyny",
		"Migocz\x0380ce Wierchy",
		"Opuszczona Zwyքka",
		"RozlegՄa Zwyքka",
		"KsiԄքycowe Szczyty",
		"Szary Szpic",
		"GoՄe Wierchy",
		"G\x0480ry Cieniste",
		"Plugawe SkaՄy",
		"Siarczane Grzbiety",
		"\x02c0elazne Wierchy"
	],
	[],
	[],
	[
		"BiaՄe Pustkowie",
		"ZmarzniԄte R\x0480wniny",
		"Morze Ʉniegu",
		"BiaՄe Uroczysko",
		"Srebrne R\x0480wniny",
		"Wyj\x0380ce Pustkowia",
		"Srebrne PՄaszczyzny",
		"Wiecznozimie",
		"ZamarzniԄta P\x0480Մnoc",
		"Kant Ʉwiata",
		"Zimnokres",
		"Zimoszerze",
		"Lodowa Skaza",
		"Kolcowiatr",
		"Dolina Lodowego Ostrza",
		"Twierdza Srebrnego Piasku",
		"ZlodowaciaՄe FaՄdy",
		"Lodowy Kr\x0380g",
		"ZamarzniԄte Nory",
		"PՄaszczyzna Polarnej Zorzy",
		"Dziedzina Lodowego Palucha",
		"Nietopn\x0380ca Zmarzlina",
		"Blady Przestw\x0480r",
		"Pustynia Luster",
		"Upiorne R\x0480wniny",
		"R\x0480wniny ChՄodnego Wichru",
		"Szklista Dolina",
		"Wyj\x0380ca Pustynia",
		"Pudrowe R\x0480wniny",
		"Ʉnieքne Zaspy"
	],
	[],
	[
		"P\x0480Մnocnokresie",
		"PՄaskoziemie",
		"Mizerlandia",
		"Ʉniegoziemie",
		"Pustoziemie",
		"Wyքyny Przodk\x0480w",
		"Niebokresy",
		"Klanowe Roszczenia",
		"Surowe PՄaszczyzny",
		"P\x0480Մnocna Klanlandia",
		"P\x0480Մnocne Kresy",
		"ʄ\x0380czodzicze",
		"JaՄowisko",
		"Ragnarowe WՄoτci",
		"Pogańskie Wrzosowisko",
		"Ruffmuir",
		"Wichroziemie",
		"Angbride",
		"Belobr\x0480d",
		"Bladoziemie",
		"Nordlandia",
		"W\x0380wozowe Kopce",
		"FaՄdoτniegi",
		"Kinmere",
		"WspaniaՄonordy",
		"Mrozobr\x0480d",
		"DԄbopՄony",
		"PosԄpne JaՄowisko"
	],
	[
		"Pustoziemie",
		"Suchoziemie",
		"Spalone R\x0480wniny",
		"Czerwone Niziny",
		"Skwarne Hrabstwo",
		"ZՄota Dolina",
		"PoՄudniowy Step",
		"PoՄudniowa Skaza",
		"Sparzyzna",
		"Dolina ZbielaՄej Koτci",
		"Suchorejon",
		"Patelnia",
		"Suchokrzewie",
		"Cierniowa PrzeՄԄcz",
		"Br\x0380zowe PՄaszczyzny",
		"ZՄowieszcza WՄoτƄ",
		"Parcheim",
		"Kraina MaՄorzecza",
		"Brzytwokrzewy",
		"Gnarlheim",
		"\x02c0wirowisko",
		"Suderos",
		"Suderlandy",
		"Solsweald",
		"PՄaskowyք Rdzawego Ostrza",
		"Muskena",
		"Solstein",
		"PoՄudniowa Warta",
		"SՄońcokresy",
		"Pustopiaski",
		"Skauna",
		"Caskain",
		"Maraman",
		"Jundlandy",
		"Pogranicze"
	],
	[],
	[
		"Srebrne Piaski",
		"Martwe Piaski",
		"ZՄote R\x0480wniny",
		"Wieczne Piaski",
		"Migocz\x0380ce Piaski",
		"Spalona Pustynia",
		"Pustka",
		"PՄon\x0380ce Pustkowia",
		"PoՄudniowe Piaski",
		"Pylista Pustynia",
		"Morze Piask\x0480w",
		"Ziemia SՄońca",
		"Wielka Pustynia",
		"Nieskończone Piaski",
		"PoՄudniowa Rubieք",
		"Mamrocz\x0380ce Piaski",
		"Szepcz\x0380ce Piaski",
		"Migruj\x0380ce Piaski",
		"JԄcz\x0380ce Piaski",
		"Lτni\x0380ce Piaski",
		"Lτni\x0380ce R\x0480wniny",
		"Suche Pustkowia"
	],
	[
		"Utracona Oaza",
		"Zielone PՄycizny",
		"Szmaragdowe ZagՄԄbie",
		"PerՄa PoՄudnia",
		"Owocowe PՄycizny",
		"Är\x0480dՄa \x02c0ycia",
		"Dar Bog\x0480w",
		"Zbawienie Proroka",
		"Mokre Ziemie"
	]
];
gt.Const.Strings.Distance <- [
	"blisko",
	"niedaleko",
	"kawałek drogi",
	"sporo drogi",
	"daleko",
	"bardzo daleko"
];
gt.Const.Strings.PartyStrength <- [
	"Żałosna",
	"Słaba",
	"Średnia",
	"Silna",
	"Niebezpieczna",
	"Zabójcza",
	"Niepokonana"
];
gt.Const.Strings.EngageEnemyNumbers <- [
	"Kilka",
	"Trochę",
	"Sporo",
	"Wiele",
	"Mnóstwo"
];
gt.Const.Strings.InventoryHeader <- [
	"Osioł",
	"Wózek",
	"Furmanka",
	"Duży Wóz"
];
gt.Const.Strings.InventoryUpgradeHeader <- [
	"Kup Wózek",
	"Kup Furmankę",
	"Kup Duży Wóz"
];
gt.Const.Strings.InventoryUpgradeText <- [
	"kupić wózek",
	"kupić furmankę",
	"kupić duży wóz"
];
gt.Const.Strings.InventoryUpgradeCosts <- [
	"5,000",
	"10,000",
	"20,000"
];
gt.Const.Strings.PerkName <- {
	Bullseye = "Sokole Oko",
	Ballistics = "Balistyka",
	Berserk = "Berserker",
	DevastatingStrikes = "Wyniszczające Ataki",
	KillingFrenzy = "Szał Zabijania",
	ShieldBash = "Uderzenie Tarczą",
	Brawny = "Krzepki",
	Stalwart = "Rosły",
	Taunt = "Drwina",
	Steadfast = "Wytrwały",
	Colossus = "Kolos",
	ShieldExpert = "Ekspert Tarczy",
	NineLives = "Dziewięć Żywotów",
	BatteringRam = "Taran",
	BattleForged = "Zaprawiony w Boju",
	BagsAndBelts = "Sakwy i Troki",
	Student = "Uczeń",
	Zweihander = "Zweihander",
	Pathfinder = "Traper",
	FortifiedMind = "Twardy Umysł",
	Captain = "Sierżant",
	InspiringPresence = "Inspirator",
	QuickHands = "Zręczne Dłonie",
	CripplingStrikes = "Okulawiające Ataki",
	Duelist = "Pojedynkowicz",
	Nimble = "Zwinny",
	Dodge = "Unik",
	HoldOut = "Prężność",
	Anticipation = "Przewidywanie",
	SteelBrow = "Stalowe Czoło",
	CoupDeGrace = "Kat",
	Weaponmaster = "Mistrz Broni",
	FastAdaption = "Szybka Adaptacja",
	SunderingStrikes = "Rozrywające Ataki",
	BattleFlow = "Bitewna Seria",
	HeadHunter = "Łowca Głów",
	RallyTheTroops = "Pokrzepienie Towarzyszy",
	Fearsome = "Przerażający",
	Indomitable = "Niezłomny",
	Debilitate = "Osłabienie",
	Footwork = "Praca Nóg",
	Rotation = "Rotacja",
	Underdog = "Przegrany",
	Recover = "Odzyskanie Sił",
	Gifted = "Uzdolniony",
	Adrenaline = "Adrenalina",
	Backstabber = "Skrytobójca",
	LoneWolf = "Samotny Wilk",
	ReachAdvantage = "Przewaga Zasięgu",
	Overwhelm = "Przytłoczenie",
	Relentless = "Nieustępliwy",
	SpecBow = "Mistrzostwo - Łuki",
	SpecCrossbow = "Mistrzostwo - Kusze i Broń Palna",
	SpecThrowing = "Mistrzostwo - Broń Miotana",
	SpecAxe = "Mistrzostwo - Topory",
	SpecCleaver = "Mistrzostwo - Tasaki",
	SpecDagger = "Mistrzostwo - Sztylety",
	SpecSword = "Mistrzostwo - Miecze",
	SpecSpear = "Mistrzostwo - Włócznie",
	SpecPolearm = "Mistrzostwo - Broń Drzewcowa",
	SpecHammer = "Mistrzostwo - Młoty",
	SpecMace = "Mistrzostwo - Maczugi",
	SpecFlail = "Mistrzostwo - Cepy"
};
gt.Const.Strings.PerkDescription <- {
	Relentless = "Nie zwalniaj! Przez cały czas twoja Inicjatywa jest zmniejszona tylko o [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] nagromadzonego Zmęczenia, zamiast całości. Ponadto używanie polecenia \'Czekaj\' nie będzie się już wiązało z karą do Inicjatywy w następnej rundzie.",
	Rotation = "Odblokowuje umiejętność \'Rotacja\', która pozwala dwóm postaciom zamienić się miejscami, ignorując Strefę Kontroli, o ile żadna z tych postaci nie jest ogłuszona, zakorzeniona lub w jakiś inny sposób unieruchomiona.",
	Footwork = "Odblokowuje umiejętność \'Praca Nóg\', która dzięki zwinnej pracy nóg pozwala opuścić Strefę Kontroli bez aktywowania darmowego okazyjnego ataku.",
	Debilitate = "Odblokowuje umiejętność \'Osłabienie\', która przygotowuje twój następny atak do osłabienia celu na jedną turę, zmniejszając jego zdolność do zadawania obrażeń o [color=" + this.Const.UI.Color.NegativeValue + "]-50%[/color].",
	Indomitable = "Odblokowuje umiejętność \'Niezłomny\', która na jedną turę daje [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] redukcji obrażeń i niewrażliwość na ogłuszenie, odrzucenie w tył lub przyciągnięcie.",
	RallyTheTroops = "Odblokowuje umiejętność \'Pokrzepienie Towarzyszy\', która potrafi natchnąć uciekających sojuszników i podnieść morale wszystkich pobliskich sojuszników do stabilnego poziomu. Im wyższa Stanowczość postaci używającej tej umiejętności, tym większa szansa na powodzenie.",
	Adrenaline = "Odblokowuje umiejętność \'Adrenalina\', która stawia cię na przedzie kolejki tur w następnej rundzie, byś mógł wykonać ruch przed wrogiem. Poczuj adrenalinę biegnącą w twoich żyłach!",
	Fearsome = "Spraw, aby rozpierzchli się i uciekali! Każdy atak zadający co najmniej 1 punkt obrażeń zdrowia wyzwala test morale dla przeciwnika z karą równą [color=" + this.Const.UI.Color.NegativeValue + "]15%[/color] twojej Stanowczości, podczas gdy normalnie taki test wykonywany jest bez żadnej kary i przy minimalnie 15 punktach obrażeń.",
	HeadHunter = "Celuj w głowę! Trafienie celu w głowę gwarantuje ci, że kolejny atak również trafi w głowę. Trafienie lub chybienie celu resetuje efekt.",
	SunderingStrikes = "Skuteczność wobec Pancerza zostaje zwiększona o [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] dla każdej użytej broni.",
	FastAdaption = "Dostosuj się do ruchów przeciwnika! Otrzymasz dodatkowe, kumulujące się [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] szansy na trafienie z każdym atakiem, który chybi przeciwnika. Premia jest resetowana po skutecznym trafieniu w cel.",
	Weaponmaster = "Wszystkie ataki kosztują cię [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color] Zmęczenia, a kondycja broni zmniejsza się o połowę wolniej. Tańcz wdzięcznie z bronią i niech każde trafienie się liczy. ",
	CoupDeGrace = "Zdaje dodatkowe [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] obrażeń celom, które już otrzymały jakieś rany, jak np. złamana ręka.",
	SteelBrow = "Trafienia w głowę już nie powodują obrażeń krytycznych dla tej postaci, co także zmniejsza znacznie szansę na wyniszczające rany głowy.",
	Anticipation = "Będąc zaatakowanym z broni dystansowej zyskujesz [color=" + this.Const.UI.Color.PositiveValue + "]1 + 10% swojej bazowej Obrony dystansowej[/color] jako premię do Obrony dystansowej na każde pole odległości między tobą, a atakującym. Jednak zawsze będzie to przynajmniej [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] do Obrony dystansowej.",
	HoldOut = "Trzymaj się! Każdy negatywny efekt o ograniczonym czasie działania (np. Krwawienie, Urok) trwa krócej o [color=" + this.Const.UI.Color.NegativeValue + "]1[/color] turę. Efekty, których siła słabnie z czasem (jak Goblińska Trucizna) od samego początku są w swoim najsłabszym stadium.",
	Dodge = "Jestem dla ciebie zbyt szybki! Zyskaj [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] obecnej inicjatywy postaci jako premię do Obrony w zwarciu i Obrony dystansowej.",
	Nimble = "Specjalizuj się w lekkim pancerzu! Zwinnie unikając i parując ataki, zamień każde trafienie w draśnięcie. Otrzymane obrażenia zdrowia są pomniejszone nawet o [color=" + this.Const.UI.Color.PositiveValue + "]60%[/color], choć ta wartość pomniejszona jest wykładniczo o całkowitą karę do maksymalnego Zmęczenia od hełmów i zbroi powyżej [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] punktów. Im lżejszy pancerz, tym bardziej na tym skorzystasz.\n\nTalent \'Krzepki\' nie ma wpływu na ten talent.\n\nNie dotyczy obrażeń od ataków psychicznych i wynikających z różnych efektów, jak np. trucizna czy krwawiące rany, choć czasem pomaga ich uniknąć.",
	BattleForged = "Specjalizuj się w ciężkiej zbroi! Otrzymane obrażenia pancerza zostają pomniejszone o wartość procentową równą [color=" + this.Const.UI.Color.PositiveValue + "]5%[/color] twojego obecnego całkowitego pancerza - sumy pancerza ciała i głowy. Im cięższa zbroja i hełm, tym więcej skorzystasz.\n\nNie dotyczy obrażeń od ataków psychicznych i wynikających z różnych efektów, jak np. trucizna czy krwawiące rany, choć czasem pomaga ich uniknąć.",
	Duelist = "Stań się jednością ze swoją bronią i celuj w słabe punkty! Gdy masz drugą rękę wolną, lub niesiesz w niej przedmiot do rzucania (np. sieć), dodatkowe [color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color] zadawanych przez ciebie obrażeń będzie ignorować pancerz. Nie działa z bronią dwuręczną.",
	CripplingStrikes = "Okulaw swoich wrogów! Zmniejsza o [color=" + this.Const.UI.Color.NegativeValue + "]33%[/color] próg obrażeń do zadawania ran i kontuzji, zarówno dla ataków w zwarciu, jak i dystansowych.",
	QuickHands = "Tego szukałeś? Raz na każdą turę wymienianie przedmiotów w walce, poza tarczami, nie będzie cię kosztować Punktów Akcji.",
	Bullseye = "W dziesiątkę! Kara do szansy na trafienie dla broni dystansowej, gdy nie masz czystej przeciwnika na czystej linii strzału, zostaje pomniejszona z [color=" + this.Const.UI.Color.NegativeValue + "]75%[/color] do [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color].",
	Ballistics = "Kara do szansy trafienia za odległość od celu jest pomniejszona o [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] na każde pole.",
	Berserk = "RAAARGH! Raz na turę, po zabiciu wroga, natychmiastowo odzyskujesz [color=" + this.Const.UI.Color.PositiveValue + "]4[/color] Punkty Akcji. Postacie nie mogą odzyskać więcej, niż ich maksymalna pula Punktów Akcji i nie więcej niż 4 za jeden atak.",
	BattleFlow = "Raz na turę zabicie przeciwnika obniża twoje obecne zmęczenie o [color=" + this.Const.UI.Color.NegativeValue + "]-25%[/color] podstawowego maksymalnego zmęczenia (zanim doliczone zostaną kary za pancerz).",
	DevastatingStrikes = "Wszystkie zadawane obrażenia zostają zwiększone o [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] dla każdej używanej broni. Cóż teraz może stanąć ci na drodze?",
	KillingFrenzy = "Wpadnij w szał zabijania! Zabicie wroga zwiększa zadawane przez ciebie obrażenia o [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color] na 2 tury. Nie kumuluje się, jednak kolejne zabójstwo odnowi licznik czasu.",
	ShieldBash = "Odepchnięcie tarczą teraz dodatkowo zadaje [color=" + this.Const.UI.Color.DamageValue + "]10 - 25[/color] obrażeń (50% skuteczności przeciw pancerzowi) oraz [color=" + this.Const.UI.Color.DamageValue + "]10[/color] Zmęczenia celowi, a użycie umiejętności kosztuje o 10 Zmęczenia mniej.",
	Brawny = "Kara do Zmęczenia i Inicjatywy od noszenia zbroi i hełmu zostaje obniżona o [color=" + this.Const.UI.Color.NegativeValue + "]30%[/color].",
	Stalwart = "Niewrażliwość przeciwko odrzuceniu w tył lub przyciągnięciu. Dotyczy umiejętności takich jak Odepchnięcie, Zahaczenie i innych, które zmieniają pozycję postaci.",
	Steadfast = "Otrzymywanie zwykłych ciosów już nie generuje zmęczenia. Nie dotyczy ataków, które same w sobie mają zwiększać zmęczenie.",
	Taunt = "Odblokowuje umiejętność \'Wydrwij\', która sprawia, że cel podejmie akcje ofensywne, zamiast obronnych i chętniej zaatakuje drwiącą z niego postać, niż jakąś inną, potencjalnie bardziej narażoną.",
	Colossus = "No dawaj! Zdrowie zostaje zwiększone o [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color], co również obniża szansę na otrzymanie wyniszczających ran i kontuzji podczas zostania trafionym.",
	ShieldExpert = "Naucz się lepiej zbijać ciosy, zamiast blokować je na wprost.\n\nPremia do obrony od tarczy zostaje zwiększona o [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color]. To dotyczy również dodatkowej premii do obrony od umiejętności \'Ściana Tarcz\'.\n\nOtrzymane obrażenia tarczy zostają zmniejszone o [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] do minimum 1.\n\nUmiejętność \'Odepchnij\' otrzymuje [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color] do szansy trafienia.",
	NineLives = "Raz na bitwę, podczas otrzymywania śmiertelnego ciosu, przeżyjesz z kilkoma punktami zdrowia, a wszelkie efekty zadające obrażenia z czasem (Krwawienie, Trucizna itp.) zostaną usunięte. Następne trafienie zapewne cię zabije, ale podwyższone aż do następnej tury atrybuty obrony pomogą ci nieco dłużej przetrwać.",
	BatteringRam = "Niewrażliwość na ogłuszenie.",
	BagsAndBelts = "Odblokuj dwa dodatkowe miejsca w swojej podręcznej sakwie, aby pomieścić wszystkie twoje ulubione rzeczy. Przedmioty w sakwie, za wyjątkiem broni dwuręcznej, nie dają już kary do maksymalnego Zmęczenia.",
	Student = "Wszystkiego można się nauczyć, gdy się człowiek przyłoży. Zdobywasz o [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] więcej doświadczenia z bitew. Na jedenastym poziomie postaci zyskasz dodatkowy punkt talentów, a ten talent przestanie działać.\n\nRozgrywając scenariusz \'Łowcy Głów\', twoi zadłużeni otrzymają zwrotny punkt talentów na siódmym poziomie postaci.",
	Gifted = "Żywot najemnika łatwo przychodzi, gdy jesteś naturalnie uzdolnionym. Natychmiastowo zyskujesz awans na wyższy poziom, aby móc zwiększyć atrybuty postaci o maksymalne wartości, jednak nie otrzymujesz dodatkowego talentu.",
	Zweihander = "Koszty zmęczenia dla wszystkich broni dwuręcznych zostają obniżone o [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color].",
	Pathfinder = "Naucz się poruszać po trudnym terenie. Koszty Punktów Akcji ruchu na każdym terenie zostają obniżone o [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] do minimum 2 Punktów Akcji na jedno pole, a koszt Zmęczenia jest zredukowany o połowę. Zmienianie wysokości również nie kosztuje już dodatkowych Punktów Akcji.",
	FortifiedMind = "Żelazną wolę niełatwo jest zachwiać. Stanowczość zostaje zwiększona o [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color].",
	Captain = "Użyj sierżanta na polu bitwy, jako przedłużenie swojego dowództwa i aby utrzymać ludzi w szyku. Sojusznicy w zasięgu 5 pól otrzymają [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] Stanowczości tej postaci jako premię do własnej Stanowczości, maksymalnie do poziomu Stanowczości tej postaci.\n\nNie kumuluje się - liczyć się będzie sierżant z największą Stanowczością.",
	InspiringPresence = "Wielki przywódca inspiruje swych ludzi, aby dali z siebie wszystko i pokonali swe słabości. Sojusznicy rozpoczynają bitwę z wysokimi morale, chyba że cechy charakteru im to uniemożliwiają.",
	Underdog = "Idzie się przyzwyczaić. Ta postać już nie otrzymuje kary do obrony wynikającej z bycia otoczonym przez przeciwników. Jeżeli przeciwnik ma talent \'Skrytobójca\', efekt tego talentu jest negowany i obowiązuje normalna kara za bycie otoczonym.",
	Recover = "Odblokowuje umiejętność \'Odzyskaj Siły\', która pozwala odpocząć przez jedną turę, aby obniżyć nagromadzone Zmęczenie o [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color].",
	Backstabber = "Szlachetnością nie wygrywa się bitew, a dźganiem w czułe miejsca - tak. Premia do szansy na trafienie w walce w zwarciu zostaje zwiększona do [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] na każdego sojusznika, który stoi obok wroga.",
	LoneWolf = "Najlepiej pracuje mi się samodzielnie. Gdy w odległości 3 pól nie ma żadnego sojusznika, zyskujesz [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] premii do Ataku w zwarciu, Ataku dystansowego, Obrony w zwarciu, Obrony dystansowej i Stanowczości.",
	ReachAdvantage = "Naucz się wykorzystywać przewagę zasięgu dużych broni, aby powstrzymać wroga przed zbliżeniem się na tyle, by skutecznie zadał cios.\n\nKażde twoje trafienie bronią dwuręczną daje ci jeden, kumulujący się efekt \'Przewagi Zasięgu\', który zwiększa twoją Obronę w zwarciu o [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color]. Efekt może zostać nałożony maksymalnie 5 razy na turę i trwa do następnej tury tej postaci. Pojedynczy atak trafiający wiele celów może nałożyć efekt kilkukrotnie za jednym razem.\n\nJeżeli odłożysz broń, tracisz wszystkie efekty.",
	Overwhelm = "Naucz się wykorzystywać swoją wysoką Inicjatywę i nie utrudnij wrogowi skuteczne atakowanie przytłaczając go własnymi atakami!\n\nWraz z każdym twoim atakiem, trafionym lub chybionym, wykonanym przeciwko wrogowi, który wykonuje ruch po tobie w danej rundzie, nakładasz na niego efekt \'Przytłoczony\', który obniża jego Atak w zwarciu i Atak dystansowy o [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] na jedną turę.\n\nEfekt kumuluje się z każdym atakiem i może być nałożony na wiele celów jednocześnie za jednym razem.",
	SpecBow = "Opanuj sztukę łucznictwa i szycia we wrogów strzałami z daleka. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\nZasięg wzroku i maksymalny zasięg strzału łuków zostają zwiększone o [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color].",
	SpecCrossbow = "Opanuj kusze oraz broń palną i naucz się, w jakie miejsca celować najlepiej. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\nDodatkowe [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] obrażeń zadanych kuszami ignoruje pancerz.\n\nKoszt przeładowania rusznic wynosi teraz [color=" + this.Const.UI.Color.NegativeValue + "]6[/color] Punktów Akcji, dzięki czemu można nimi strzelać co turę, a nie co dwie tury.",
	SpecThrowing = "Opanuj broń miotaną, aby ranić i zabijać wrogów zanim się zbliżą. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\nObrażenia zostają zwiększone o [color=" + this.Const.UI.Color.PositiveValue + "]40%[/color] podczas atakowania celu oddalonego o 2 pola.\n\nObrażenia zostają zwiększone o [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] podczas atakowania celu oddalonego o 3 pola.",
	SpecAxe = "Opanuj walkę toporami i niszczenie tarcz. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\n\'Rozłupanie Tarczy\' zadaje teraz o [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] więcej obrażeń, jeśli używa się topora.\n\n\'Okrężny Zamach\' ma [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] do szansy na trafienie.\n\nDługi topór nie ma już kary do atakowania bezpośrednio przyległych celów.",
	SpecCleaver = "Opanuj tasaki, aby zadawać makabryczne rany. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\nObrażenia od krwawienia zadawane przez tasaki i bicze zostają podwojone odpowiednio do [color=" + this.Const.UI.Color.PositiveValue + "]10[/color] oraz [color=" + this.Const.UI.Color.PositiveValue + "]20[/color] na turę.\n\nRozbrojenie ma tylko połowę kary do szansy trafienia.",
	SpecDagger = "Opanuj szybkie i zabójcze sztylety. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\n\'Dźgnij\', \'Przekłuj\' i \'Zabójczy Cios\' mają zmniejszony koszt Punktów Akcji, aby umożliwić wykonanie jednego dodatkowego ataku na turę.",
	SpecSword = "Opanuj sztukę walki na miecze, używając błędów przeciwnika na swoją korzyść. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\n\'Riposta\' nie ma już kary do szansy na trafienie\n\n\'Rozetnij\' ma o [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] niższy próg na zadawanie ran i kontuzji.\n\n\'Rozłup\' i \'Wymach\' zyskują [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] do szansy na trafienie.",
	SpecSpear = "Opanuj walkę włóczniami i trzymanie wroga w ryzach. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\n\'Ściana Włóczni\' nie zostaje już wyłączona, gdy wróg ją przełamie. Zamast tego nadal daje darmowe ataki na każdego kolejnego wroga, który spróbuje wejść w Strefę Kontroli.\n\nSpisa i Widły Bojowe nie mają już kary do atakowania bezpośrednio przyległych celów.",
	SpecPolearm = "Opanuj broń drzewcową i trzymanie wroga w ryzach. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\nKoszt Punktów Akcji używania umiejętności broni drzewcowych zostaje pomniejszony do [color=" + this.Const.UI.Color.NegativeValue + "]5[/color]. Broń drzewcowa nie ma już kar do atakowania wrogów bezpośrednio przyległych.",
	SpecHammer = "Opanuj młoty i walkę przeciwko ciężko opancerzonym przeciwnikom. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\n\'Zniszcz Pancerz\' i \'Zdemoluj Pancerz\' zadają [color=" + this.Const.UI.Color.PositiveValue + "]33%[/color] więcej obrażeń pancerzowi.\n\n\'Roztrzaskaj\' otrzymuje [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] do szansy na trafienie.\n\nMłot na drzewcu nie ma już kary do atakowania bezpośrednio przyległych celów.",
	SpecMace = "Opanuj maczugi, aby wytłuc na wrogach posłuszeństwo, czy są opancerzeni, czy nie. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\n\'Ogłusz\', \'Przewróć\' i \'Powal\' mają [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] szansy na ogłuszenie celu, o ile nie jest niewrażliwy.\n\nBuława na drzewcu nie ma już kary do atakowania bezpośrednio przyległych celów.",
	SpecFlail = "Opanuj cepy i omijanie tarczy przeciwnika. Umiejętności generują o [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] mniej Zmęczenia.\n\n\'Smagaj\' i \'Gradobicie\' ignorują premię do obrony od tarcz.\n\n\'Wymłóć\' otrzymuje [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] do szansy na trafienie."
};
gt.Const.Strings.Tooltip <- {
	World = {
		Hint_FocusParty = "Kliknij, by skupić się na oddziale",
		Hint_FocusLocation = "Kliknij, by skupić się na lokacji"
	},
	Tactical = {
		Hint_FocusCharacter = "Kliknij, by skupić się na postaci",
		Hint_CannotChangeItemInCombat = "Nie można zmienić w trakcie bitwy",
		Hint_OnlyActiveCharacterCanChangeItemsInCombat = "Tylko postać aktualnie wykonująca ruch może zmienić przedmioty"
	}
};

