local gt = this.getroottable();

if (!("World" in gt.Const))
{
	gt.Const.World <- {};
}

if (!("Location" in gt.Const.World))
{
	gt.Const.World.LocationNames <- {};
}

gt.Const.World.LocationNames.VillageWestern <- [
	"Wiesendorf",
	"Elkshorn",
	"Dunkelwald",
	"Altdorf",
	"Wallendorf",
	"Auen",
	"Kallesheim",
	"Windau",
	"Minarken",
	"Durbach",
	"Almor",
	"Weilau",
	"Wedemark",
	"Heidemark",
	"Bogenheim",
	"Sonneberg",
	"Reusdorf",
	"Langenthal",
	"Thurgau",
	"Baden",
	"Tordorf",
	"Waldrode",
	"Rauthal",
	"Isenhagen",
	"Hagen",
	"Malmkrog",
	"Ferlangen",
	"Radeln",
	"Arbegen",
	"Hamruden",
	"Schoenberg",
	"Eisenstein",
	"Tadeln",
	"Hammererden",
	"Segeland",
	"Ulhart",
	"Felmern",
	"Weidenau",
	"Rietberg",
	"Ottendorf",
	"Thalheim",
	"Dornheim"
];
gt.Const.World.LocationNames.CityWestern <- [
	"Albstadt",
	"Almborg",
	"Dulmen",
	"Marburg",
	"Ulmen",
	"Dornen",
	"Karnstein",
	"Wallstadt"
];
gt.Const.World.LocationNames.GuardTower <- [
	"Stara Strażnica",
	"Strażnica",
	"Wieża Burzowarty",
	"Wieża Czarnostraży",
	"Wieża Żelaznego Serca",
	"Wieża Drewnogrodu",
	"Twierdza Pogórza",
	"Warownia %randomname%a",
	"Warta Wichroziemi",
	"Wieża Kamiennej Pięści",
	"Twierdza Strażnika",
	"Wieża Heimwart",
	"Starożytna Czatownia",
	"Wieża Zguby Orków"
];
gt.Const.World.LocationNames.Castle <- [
	"Zamek Siedmiu Wzgórz",
	"Zamek Kronland",
	"Zamek Sturmwind",
	"Zamek Berland",
	"Zamek Heimland",
	"Zamek Mortham",
	"Zamek Walmer",
	"Zamek Hornburg",
	"Zamek Reikmark",
	"Zamek Starkland",
	"Cytadela Wallstein",
	"Zamek Dorngard",
	"Zamek Kragburg"
];
gt.Const.World.LocationNames.BanditCamp <- [
	"Czarny Fort",
	"Obóz Tysiąca Włóczni",
	"Fort Wisielca",
	"Fort Truposza",
	"Obóz Czarnych Ogarów",
	"Fort Grozy",
	"Obóz Skrytego Noża",
	"Obóz Mężobójcy",
	"Nora Wyrzutków",
	"Nora Sztyletu",
	"Kryjówka Mordercy",
	"Legowisko Rabusiów",
	"Kryjówka Bezprawych",
	"Leże Zbójców",
	"Obóz Maruderów",
	"Obóz Łupieżców",
	"Obóz Plądrowników",
	"Nora Żmij",
	"Obóz Czerwonych Noży",
	"Nora Czerwonych Orłów",
	"Dwór Krwawych Wilków",
	"Obóz Wolnego Ludu",
	"Nora Czerwonego Księżyca",
	"Obozowisko Trzydziestu Toporów",
	"Obozowisko Najeźdźców",
	"Sztyletowe Schronienie",
	"Spiżowe Legowisko",
	"Jaskinia Długich Sztyletów",
	"Przystań Zagubionych Dusz",
	"Nora Wyrzutków",
	"Leże Bandytów",
	"Kryjówka Popielatogłowych",
	"Garnizon Strzępiastych Kling",
	"Schronienie Poszukiwanych",
	"Azyl Chłodnych Serc",
	"Obóz Zmierzchu",
	"Garnizon Parcianych",
	"Schronienie Niegodziwców",
	"Upadek Prawych",
	"Legowisko Ścinaczy Głów",
	"Kryjówka Pałowników",
	"Obóz Włóczęgów",
	"Bractwo Noża",
	"Obóz Szkarłatnych Maruderów",
	"Kryjówka Banitów",
	"Obóz Zuchwałych Braci",
	"Azyl Kieszonkowców",
	"Kryjówka Zbójców",
	"Leże Rabusiów",
	"Obozowisko Włamywaczy",
	"Nora Czarnych Serc",
	"Bastion Renegatów",
	"Kryjówka Wygnańców",
	"Bastion Wygnanych",
	"Legowisko Nożowników",
	"Jama Podrzynaczy Gardeł",
	"Obóz Maczugi"
];
gt.Const.World.LocationNames.OrcCamp <- [
	"Naragash",
	"Bara Garash",
	"Bara Karagim",
	"Bara Maratuk",
	"Skallebar Turum",
	"Urogash Morat",
	"Maruk Blot",
	"Ghul Blagash",
	"Rubrokk",
	"Korashtum",
	"Skallehalden",
	"Wargash Sapat",
	"Bara Skrabsragash",
	"Obarakk",
	"Gulgash Ghul",
	"Wargasharak",
	"Rurak Barat",
	"Garagash Rotak",
	"Eregash Hartak",
	"Hurgash Ghaal",
	"Wagash Blot",
	"Morat Gragagash",
	"Urot Gash",
	"Vrek Sapat",
	"Varuk Ghul",
	"Skarsnik Blot",
	"Mogtul Garash",
	"Shagol Vrak",
	"Vargash Hartak",
	"Uratosh Turum",
	"Turbagash",
	"Toghat Blok",
	"Urug Wargash",
	"Guhlgarash",
	"Varghul Blot",
	"Glush Zugbu",
	"Uruk Zuga",
	"Grat Bogat",
	"Grug Zugar",
	"Darak Ghul",
	"Bloga Kurk",
	"Za-Zaruk",
	"Berek Wagash",
	"Graurukash",
	"Wuruk Zagash",
	"Blukat Gash",
	"Duruk Hartak"
];
gt.Const.World.LocationNames.GoblinBase <- [
	"Negex Zum",
	"Rotox Grubb",
	"Finex Thum",
	"Nul Zadux",
	"Thelox Grubb",
	"Zulim Bax",
	"Thum Niox",
	"Nexex Kadox",
	"Grubbzugat",
	"Nazatux",
	"Lazanix",
	"Shanarax",
	"Noxox",
	"Shex Shex Shex",
	"Shalax Tchech",
	"Thelox Tcharax",
	"Nul Sharax",
	"Haraz Nox",
	"Zugghat Thul",
	"Grubbox Thum",
	"Visnik Zum",
	"Thum Tux",
	"Grisnik Kadox",
	"Zugat Nazat",
	"Nozik Grubb",
	"Xin Zatox",
	"Zatox Thum",
	"Bazak Nox",
	"Zugtak",
	"Jadaz Grat",
	"Wirdlok Zum",
	"Zatak Nul",
	"Velok Kazul",
	"Nagraz Nox",
	"Thul Kazum"
];
gt.Const.World.LocationNames.Crypt <- [
	"Grobowiec Szalonego Króla",
	"Dawno Zapomniany Grobowiec",
	"Grobowiec Lordów",
	"Grobowiec Ludzi z Gór",
	"Krypta Włóczęgi",
	"Zniszczony Grobowiec",
	"Ukryta Świątynia",
	"Grobowiec %randomnoble%a",
	"Krypta Martwych Wrót",
	"Krypta Ogara",
	"Krypta Jal-Fargi",
	"Grobowiec Wielkiego Wieszcza",
	"Grobowiec Wielu Wron",
	"Grobowiec %randomname%a {Wielkiego | Okrutnego | Tyrana}",
	"Grobowiec Pierwszych Ludzi",
	"Krypta Ogmara",
	"Koścista Ostoja",
	"Mroczna Krypta",
	"Ostatni Spoczynek",
	"Zniszczona Świątynia",
	"Grobowiec Tomba",
	"Wieczny Grobowiec",
	"Krypta Szarobrodego",
	"Piekielna Krypta",
	"Monument Beznadziei",
	"Krypta Pustych Kości",
	"Spoczynek Wyszczerzonych Czaszek",
	"Zbezczeszczona Krypta",
	"Utracona Krypta",
	"Odkopany Grobowiec",
	"Grobowiec Dawnych Królów",
	"Porywająca Krypta",
	"Grobowiec Zbielałych Kości",
	"Grobowiec Przodków",
	"Krypta Północy",
	"Grobowiec Dziadków",
	"Krypta Starszego",
	"Spoczynek Odźwiernego",
	"Grobowiec Płaczu",
	"Krypta Żałoby",
	"Katakumby Niespokoju",
	"Grób Przodków",
	"Przeklęte Mauzoleum",
	"Pieczara Umarłych",
	"Kostnica Połamanych Kości",
	"Grób Niespokoju",
	"Ostatni Spoczynek Pierwszego Króla",
	"Grobowiec Mrocznej Kniei",
	"Opuszczone Mauzoleum",
	"Krypta Grzechoczących Kości",
	"Zapominana Krypta",
	"Ponure Grobowce"
];
gt.Const.World.LocationNames.MassGrave <- [
	"Spoczynek Bez Odwrotu",
	"Grób Ostatniej Drużyny",
	"Grób Bitwy Pod Heimland",
	"Spoczynek Tysięcy",
	"Mokradło Szurających Kości",
	"Otwarty Masowy Grób",
	"Naruszony Masowy Grób",
	"Groby Zarazy",
	"Starożytne Miejsce Pochówku",
	"Odkopane Kurhany",
	"Stos Kości",
	"Spoczynek Gnijących Kości",
	"Starożytne Pole Bitwy",
	"Kotlina Białych Kości",
	"Zapomniany Masowy Grób",
	"Koniec Podróżnika",
	"Koniec Ostatniej Nadziei",
	"Zapadnięte Pole Bitwy",
	"Klęska %randomname%a",
	"Odsłonięty Masowy Grób",
	"Odkopany Stos Kości",
	"Przepełniony Grób",
	"Prowizoryczne Miejsce Pochówku",
	"Pole Kości",
	"Pola Zagłady",
	"Przekopany Masowy Grób",
	"Zbezczeszczone Pole Bitwy",
	"Pola Usiane Kośćmi",
	"Menażeria Białych Kości",
	"Przeklęte Kurhany",
	"Sępia Uczta",
	"Wygasłe Pole Bitwy",
	"Upadek Ostatniego Lorda",
	"Splądrowane Pole Bitwy",
	"Kościane Wzgórze",
	"Góry Szkieletów",
	"Ocean Kości"
];
gt.Const.World.LocationNames.VampireCoven <- [
	"Dwór Czerwonej Rzeki",
	"Sabat Czarnej Krwi",
	"Sabat Krwiopijcy",
	"Sabat Dawnych Panów",
	"Krąg Starożytnych",
	"Sabat Wątłego Księcia",
	"Krąg Nieśmiertelnych",
	"Sabat Bezśmiertnych",
	"Dom Nieśmiertelnych",
	"Dom Głodu",
	"Sabat Północy",
	"Krypta Dawnych Władców",
	"Sabat Starożytnych",
	"Zamek Nekrosawantów",
	"Sabat Koszmarów",
	"Krąg Więzów Krwi",
	"Sale Okropności",
	"Sabat Mrocznych Całunów",
	"Świątynia Nieumierających",
	"Świątynia Istot Nocy",
	"Zamek Starożytnych Umarłych",
	"Sabat Wygnanych",
	"Sabat Bez Odwrotu",
	"Krąg Wiecznej Ciemności",
	"Sabat Pełnego Księżyca",
	"Łaknienie Ghula",
	"Zapominany Sabat",
	"Dom Koszmarów",
	"Sabat Maskarady",
	"Dom Czerwonego Pragnienia",
	"Kryjówka Żarłaczy Krwi",
	"Krypta Nocnego Głodu",
	"Sabat Latającej Śmierci",
	"Dom Otchłani",
	"Dwór Czarnego Całunu",
	"Sabat Odrzutków Śmierci",
	"Sale Nieumierających",
	"Krąg Księżycowej Armii",
	"Zamek Okropności",
	"Sabat Północnego Terroru",
	"Leże Krwiopijców",
	"Twierdza Krwawych Pomiotów"
];
gt.Const.World.LocationNames.Ruins <- [
	"Spalone Ruiny",
	"Zarośnięte Fundamenty",
	"Zapomniane Ruiny",
	"Walące Się Ruiny",
	"Opuszczone Mury",
	"Zawalone Domostwa",
	"Schronienie Pośród Ruin",
	"Zamieszkałe Ruiny",
	"Ruiny Fieren",
	"Ruiny Kragenheim",
	"Ruiny Borgen",
	"Zawalone Ruiny",
	"Opuszczona Twierdza",
	"Zawalona Forteca",
	"Starożytne Ruiny",
	"Ruiny Burzowej Baszty",
	"Ruiny Baszty Czarnowody",
	"Ruiny Baszty Żelaznego Serca",
	"Ruiny Baszty Rosłości",
	"Warownia %randomname%a",
	"Ruiny Baszty Kamiennej Pięści",
	"Ruiny Baszty Strażnika",
	"Ruiny Zamku Heimwart",
	"Starożytna Czatownia",
	"Ruiny Baszty Zguby Orków",
	"Przekrzywione Głazy",
	"Zniszczone Domostwa",
	"Zniszczona Forteca",
	"Zwalone Fortyfikacje",
	"Opuszczone Szczątki",
	"Omszałe Ruiny",
	"Zawalone Schronienie",
	"Szczątki Fortecy",
	"Zapomniany Fort",
	"Zarośnięta Warownia",
	"Wyblakłe Ruiny",
	"Dawno Utracona Baszta",
	"Opuszczone Wieże",
	"Zapomniane Ruiny",
	"Opustoszałe Domostwa",
	"Zawalona Strażnica",
	"Zniszczona Warownia",
	"Ruiny z Dawnych Lat",
	"Przewrócone Głazy",
	"Zawalona Baszta",
	"Upadła Baszta",
	"Zawalona Twierdza",
	"Przewalona Strażnica",
	"Pozostałości Przodków",
	"Zniszczone Domostwa",
	"Niedokończona Forteca"
];
gt.Const.World.LocationNames.BuriedCastle <- [
	"Utracony Pałac",
	"Połknięty Zamek",
	"Zatopione Mury Markgrafu",
	"Zaginiona Baszta",
	"Przeklęta Cytadela",
	"Zasypany Zamek %randomname%a",
	"Utopiona Forteca",
	"Opuszczone Ruiny Zamku",
	"Czarna Forteca",
	"Szkarłatny Zamek",
	"Zatopiona Warownia",
	"Dom Utraconego Tronu",
	"Zasypany Pałac",
	"Bezbożny Pałac",
	"Podziemne Zacisze",
	"Forteca Zatopionego Króla",
	"Zakopany Pałac",
	"Cienisty Pałac",
	"Miasto Grobów",
	"Martwe Miasto",
	"Zamek Utraconego Króla",
	"Nekropolia",
	"Pogrzebana Cytadela",
	"Zatopione Miasto",
	"Podziemna Forteca",
	"Cienista Baszta",
	"Warownia Pod Ziemią",
	"Niedostępna Cytadela",
	"Zatopiona Twierdza Umarłych",
	"Zgładzone Miasto",
	"Pochowana Cytadela",
	"Pałac Pod Ziemią",
	"Podziemny Pałac",
	"Zaginiony Zamek Przeklętych",
	"Labirynt Umarłych",
	"Szepcząca Forteca",
	"Miasto Ciszy",
	"Wygnany Fort",
	"Zamek Bełkoczącego Księcia",
	"Zakopany Zamek",
	"Warownia Zaginionych"
];
gt.Const.World.LocationNames.Hideout <- [
	"Stara Chata %randomname%a",
	"Zapomniany Dom Drwala",
	"Kryjówka Leśnika",
	"Zapomniana Chata",
	"Zapomniane Domostwo",
	"Opuszczone Schronienie",
	"Zarośnięte Domostwo",
	"Zniszczona Zagroda",
	"Zgniły Szałas",
	"Zniszczona Chata",
	"Chatka Pustelnika",
	"Kryjówka Nożownika",
	"Zasadzka Ostrych Kling",
	"Zarośnięta Kryjówka",
	"Kryjówka Chciwych Serc",
	"Opuszczona Chata",
	"Zapadnięta Kryjówka",
	"Zarośnięta Chata Drwala",
	"Opustoszałe Schronienie",
	"Spoczynek Podróżnika",
	"Schronienie Zagubionego",
	"Zawalone Domostwo",
	"Zapomniana Chata",
	"Opuszczona Zagroda",
	"Omszałe Schronienie",
	"Zaniedbana Chata",
	"Zaniedbana Chatka",
	"Zniszczona Sadyba",
	"Utracona Chatka",
	"Zamieszkała Rudera",
	"Zapadnięta Rudera",
	"Połatana Sadyba",
	"Chatka Drwala",
	"Nędzny Barak",
	"Zniszczona Kwatera",
	"Prymitywny Barak",
	"Wątła Rudera",
	"Zgniła Kwatera",
	"Zawalona Zagroda",
	"Stęchłe Schronienie",
	"Zapadnięty Domek",
	"Prowizoryczne Schronienie",
	"Azyl Kłusownika",
	"Barak Łowczego",
	"Zapadła Kryjówka",
	"Chybotliwe Schronienie"
];
gt.Const.World.LocationNames.GreenskinCamp <- [
	"Obóz Dziesięciu Kłów",
	"Obóz Najeźdźców Żelaznego Brzegu",
	"Obóz Skroniołamców",
	"Obóz Krwiożerców",
	"Obóz Zgnilców",
	"Obóz Roztrzaskanych Toporów",
	"Obóz Dziczej Czaszki",
	"Obóz Maruderów Mrocznej Puszczy",
	"Obóz Łamignatów",
	"Nora Rzeźników",
	"Nora Postrzępionego Toporka",
	"Obóz Miażdżycieli Czaszek",
	"Obóz Szalejącej Hordy",
	"Obóz Zielonoskórych Najeźdźców",
	"Obozowisko Kościożerców",
	"Obóz Czerwonych Noży",
	"Nora Ludziożerców",
	"Obóz Płonącego Topora",
	"Warowny Obóz Piłozębnych",
	"Baza Łupieżców",
	"Główny Obóz Najeźdźców",
	"Obóz Strasznego Wrzasku",
	"Obóz Zbrojogniotów",
	"Obozowisko Murowałów",
	"Nora Żelaznych Szczęk",
	"Zgromadzenie Człekogniotów",
	"Zgromadzenie Dziesięciu Plemion",
	"Warowny Obóz Plemienia Dzika",
	"Zgromadzenie Czarnych Dłoni",
	"Garnizon Głowogniota",
	"Obozowisko Wodza",
	"Obóz Patroszycieli",
	"Obozowisko Tysiąca Zębów"
];
gt.Const.World.LocationNames.GoblinCamp <- [
	"Obóz Łowców Niewolników",
	"Leże Ostrego Zęba",
	"Kryjówka Szpikulca",
	"Nora Długich Pik",
	"Leże Czarnych Wilków",
	"Kryjówka Szpiczastych Uszu",
	"Zasadzka Ostrych Kling",
	"Kryjówka Wielu Noży",
	"Obóz Wilczej Watahy",
	"Nora Niechętnych",
	"Obóz Zielonej Grozy",
	"Obóz Zaostrzonych Kijów",
	"Kryjówka Zasadzkowiczów",
	"Obóz Zgrzytającego Noża",
	"Obóz Tysiąca Strzał",
	"Nora Dźgaczy",
	"Obóz Senatu",
	"Zasadzka Nożowników",
	"Leże Chichoczącego Zła",
	"Obóz Strzelców",
	"Obóz Latających Noży",
	"Obóz Chichoczącej Śmierci",
	"Kryjówka Truciznoroba",
	"Garnizon Okrutnego Prześladowcy",
	"Obozowisko Przyczajonych w Cieniu",
	"Nora Skrytobójców",
	"Zgrupowanie Senatu",
	"Garnizon Miotacza Trucizny",
	"Baza Łowców Niewolników",
	"Warowny Obóz Szamana",
	"Główny Obóz Łowców"
];
gt.Const.World.LocationNames.NecromancerLair <- [
	"Leże Mrocznych Rytuałów",
	"Ukryte Komnaty Nekromanty",
	"Schronienie Mistrza Marionetek",
	"Kryjówka Nekromanty",
	"Jaskinia Umarłych",
	"Leże Wygnańca",
	"Nora Nieumarłych",
	"Refugium Nekromanty",
	"Azyl Mrocznych Sztuk",
	"Leże Nekromanty",
	"Schronienie Apostaty",
	"Kryjówka Heretyka",
	"Nora Grzesznika",
	"Tajemny Krąg Poganina",
	"Schronienie Plugawego Człeka",
	"Leże Zakazanych Rytuałów",
	"Azyl Mistrza Marionetek",
	"Schronienie Wygnańca",
	"Leże Nieopisanych Okropności",
	"Kryjówka Szalonego Mistrza",
	"Schronienie Nekromanty",
	"Sadyba Reanimatora",
	"Krąg Mrocznych Mocy",
	"Tajemne Komnaty Okultysty",
	"Azyl Zakazanej Sztuki",
	"Schronienie Mrocznego Zaklinacza",
	"Nora Nienazwanych Koszmarów",
	"Sadyba Nocy",
	"Pracownia Mistrza Marionetek",
	"Zbezczeszczona Świątynia",
	"Kryjówka Zaklinacza Śmierci",
	"Kościół Mrocznego Kapłana",
	"Świątynia Nieopisanych Okropności",
	"Schronienie Apostaty",
	"Tajemna Sadyba Apostaty",
	"Azyl Duszowięźcy",
	"Leże Złaknionych Potęgi",
	"Tajemne Komnaty Obłędu",
	"Schronienie Żniwiarza",
	"Kryjówka Animatora",
	"Nora Cyrulika"
];
gt.Const.World.LocationNames.Graveyard <- [
	"Zarośnięte Nagrobki",
	"Odległe Cmentarzysko",
	"Przekrzywione Nagrobki",
	"Ukryte Cmentarzysko",
	"Opuszczony Mogilnik",
	"Stare Cmentarzysko",
	"Starożytna Nekropolia",
	"Zatopione Nagrobki",
	"Cmentarz Biedoty",
	"Prowizoryczne Miejsce Pochówku",
	"Cmentarz Niespokojnych",
	"Cmentarzysko Grzechoczących Kości",
	"Opuszczone Cmentarzysko",
	"Starożytne Cmentarzysko",
	"Zakazane Cmentarzysko",
	"Cmentarz Przodków",
	"Opuszczone Miejsce Pochówku",
	"Nadkruszone Nagrobki",
	"Przekopane Miejsce Pochówku",
	"Miejsce Pochówku Przodków",
	"Ostatni Spoczynek Nadziei",
	"Cmentarz Przodków",
	"Ukryta Nekropolia",
	"Ustronne Miejsce Pochówku",
	"Ustronny Cmentarz",
	"Omszałe Nagrobki",
	"Ostatni Spoczynek Zapomnianych",
	"Opuszczone Kurhany",
	"Groby Przodków",
	"Ostatni Spoczynek Przodków",
	"Cmentarz z Dawnych Lat",
	"Przechylone Mogiły",
	"Cmentarzysko Wrzeszczących Kamieni",
	"Odległe Nagrobki",
	"Cmentarz Starszyzny",
	"Groby Ofiar Ospy"
];
gt.Const.World.LocationNames.OrcCave <- [
	"Jaskinia Tysiąca Wrzasków",
	"Kryjówka Burzoklanu",
	"Cuchnąca Jaskinia",
	"Zamieszkała Jaskinia",
	"Niezbadana Jaskinia",
	"Nora Długiego Kła",
	"Nora Oszalałych Toporów",
	"Nora Krwawego Tasaka",
	"Kryjówka Strzępiastych Kłów",
	"Jaskinia Ilskah Ghula",
	"Jaskinia Oprawcy",
	"Jaskinia Porywacza Dzieci",
	"Leże Czarnego Niedźwiedzia",
	"Plugawa Jaskinia",
	"Pieczara Łamignata",
	"Pieczara Dzika",
	"Nora Zielonoskórych",
	"Pieczara Utraconych Krzyków",
	"Nora Łupieżców",
	"Jaskinia Mięsożerców",
	"Grota Miażdżyciela Czaszek",
	"Grota Dzikich Ludzi",
	"Grota Odrąbywacza Głów",
	"Pieczara Zielonej Śmierci",
	"Grota Gruntera",
	"Jaskinia Orków",
	"Pieczara Mięsożercy"
];
gt.Const.World.LocationNames.BarbarianShelter <- [
	"Namioty Barbarzyńców",
	"Kryjówka Wolnego Ludu",
	"Futrzane Szałasy Barbarzyńców",
	"Prowizoryczne Futrzane Szałasy",
	"Schronienie Thrallów",
	"Plemienne Chałupy",
	"Plemienne Chatki",
	"Namioty Najeźdźców",
	"Plemienne Jurty",
	"Jurty Wolnego Ludu",
	"Północne Jurty",
	"Nordyckie Szałasy",
	"Posterunek Plemion",
	"Plemienna Straż Przednia",
	"Posterunek Barbarzyńców"
];
gt.Const.World.LocationNames.BarbarianCamp <- [
	"Obozowisko Barbarzyńców",
	"Obóz Plemienny",
	"Obóz Rozbójników",
	"Jurty Łupieżców",
	"Schronienie Łowców Niewolników",
	"Północna Kryjówka",
	"Tymczasowy Obóz Barbarzyńców",
	"Kryjówka Barbarzyńców",
	"Warowny Obóz Barbarzyńców",
	"Jurty Rozbójników",
	"Schronienie Klanów",
	"Jurty Przodków",
	"Obóz Łowców Niewolników"
];
gt.Const.World.LocationNames.BarbarianSanctuary <- [
	"Zgromadzenie Czempionów",
	"Kamienie Starożytnych",
	"Obóz Wojenny Barbarzyńców",
	"Jurtowe Miasto Przodków",
	"Kamień Zgromadzeń Starszych",
	"Zgromadzenie Przodków",
	"Miejsce Mocy Barbarzyńców",
	"Obóz Wojowników Plemiennych",
	"Miejsce Rytualne Barbarzyńców",
	"Obozowisko Futrzanych Namiotów",
	"Obóz Przodków",
	"Ołtarz Ofiarny",
	"Ołtarz Przodków",
	"Obwarowane Chaty Barbarzyńców"
];
gt.Const.World.LocationNames.NomadTents <- [
	"Chatki Koczowników",
	"Pustynne Namioty",
	"Namioty Koczownicze",
	"Ukryte Namioty",
	"Kryjówka Koczownicza",
	"Przelotny Obóz",
	"Latające Namioty",
	"Schronienie Koczownicze",
	"Ruchliwe Namioty",
	"Obozowisko Koczownicze",
	"Namioty Wolnych Ludzi",
	"Złote Namioty",
	"Szkarłatne Namioty",
	"Gorejące Schronienie",
	"Wędrujące Namioty",
	"Piaskowe Namioty"
];
gt.Const.World.LocationNames.HiddenCamp <- [
	"Kryjówka Koczowników",
	"Siedlisko Koczowników",
	"Ukryte Obozowisko",
	"Obóz Koczowników",
	"Prowizoryczny Obóz",
	"Obóz Podróżników",
	"Pustynne Schronienie",
	"Schronienie Pośród Skał",
	"Posterunek Pustynnych Najeźdźców",
	"Obóz Wolnych Wędrowców",
	"Schronienie Koczowników",
	"Obóz Pustynnej Plagi",
	"Schronienie Najeźdźców",
	"Obóz Czerwonych Piasków",
	"Obóz Płonących Piasków",
	"Obóz Białych Piasków",
	"Obozowisko Wolnych Dusz",
	"Kryjówka Złotego Słońca",
	"Kryjówka Zmiennych Piasków",
	"Obozowisko Pustynnych Najeźdźców"
];
gt.Const.World.LocationNames.NomadTentCity <- [
	"Miasto Koczowników",
	"Miasto Namiotów",
	"Obóz Porannego Słońca",
	"Miasto Namiotów Pustynnych Wojowników",
	"Wędrujące Miasto",
	"Obóz Gorejącego Słońca",
	"Konklawe Koczowników",
	"Wędrujące Królestwo",
	"Obóz Martwej Oazy",
	"Miasto Złotych Piasków"
];
gt.Const.World.LocationNames.AncientRuins <- [
	"Pozostałości Imperium",
	"Pozostałości Dawnej Przeszłości",
	"Zatopione Ruiny",
	"Połknięte Ruiny",
	"Pyliste Mury",
	"Szczątki Przykryte Piaskiem",
	"Smagane Piaskiem Ruiny",
	"Wyblakłe Kamienie",
	"Spalone Słońcem Ruiny",
	"Starożytne Ruiny",
	"Zniszczone Mury Imperium",
	"Ruiny Dawnych Lat",
	"Przykryte Piaskiem Ruiny",
	"Upadłe Piaskowce",
	"Niknące Kamienie",
	"Rumowisko Starożytnych Czasów",
	"Pożarta Osada",
	"Spalone Mury",
	"Mury Pod Piachem"
];

